"use client";

import Image from "next/image";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ChoiceQuestion, ClassificationChallenge, FocusFrameworkRoadmap, FocusSpec, InterviewDialogueExample, InterviewDynamicsGuide, OrderQuestion, PassiveLearningCards, PredictionChecklist, TabbedCodeView, TabbedConceptView } from "@/components/learning/learning-interactions";
import { MeetingRoomSchedulerSimulator } from "@/components/simulations/meeting-room-scheduler-simulator";
import { meetingRoomClassDiagrams } from "@/lib/class-diagrams";

const passive: Record<string, { intro: string; items: { title: string; body: string }[]; conclusion?: string }> = {
  "meeting-incomplete": { intro: "‘Schedule a meeting room’ leaves the decisions that determine correctness unstated.", items: [{title:"Suitability",body:"Capacity and equipment must both pass."},{title:"Conflict",body:"The interval boundary decides whether touching meetings are legal."},{title:"Selection",body:"Several valid rooms need one deterministic winner."},{title:"Cancellation",body:"Ownership and unchanged-state behavior must be explicit."}], conclusion:"Clarify observable behavior before naming classes." },
  "meeting-answers": { intro: "Each interviewer answer becomes one testable rule.", items: [{title:"Actions",body:"Schedule one request and let only its organizer cancel."},{title:"Suitability",body:"Capacity is sufficient and every required equipment value exists."},{title:"Time",body:"Use [start, end); touching boundaries do not overlap."},{title:"Winner",body:"Choose lowest capacity, then lowest room ID."},{title:"Rejection",body:"No room, wrong owner, and unknown ID change nothing."},{title:"Scope",body:"One office time zone, one sequential in-memory process."}] },
  "meeting-entity-transition": { intro: "Extract nouns, then keep only candidates that own a rule, changing state, or one meaningful value.", items: [{title:"Values",body:"TimeSlot and MeetingRequest carry stable facts."},{title:"State owner",body:"Room owns one ordered schedule."},{title:"Policy",body:"RoomSelectionStrategy compares qualified rooms."},{title:"Coordinator",body:"MeetingScheduler owns IDs, lookup, scheduling, and cancellation."}], conclusion:"Calendar, organizer, and attendee remain outside this confirmed scope." },
  "meeting-modeling-vocabulary": { intro: "Choose the smallest model that can protect the rule.", items: [{title:"Class",body:"Owns identity, state, or important behavior."},{title:"Interface",body:"Defines replaceable behavior."},{title:"Enum",body:"Names a small fixed set."},{title:"Immutable value",body:"Keeps related stable facts together."},{title:"Field",body:"A simple value inside another type."},{title:"Leave out",body:"Has no responsibility in this version."}] },
  "meeting-design-method": { intro: "Repeat the same derivation for every class.", items: [{title:"Requirement",body:"Start from a confirmed observable rule."},{title:"Responsibility",body:"Give it to the object with the needed information."},{title:"State",body:"Store only what that rule needs."},{title:"Behavior",body:"Keep checks and changes beside the state."},{title:"API",body:"Expose use cases, not mutable internals."},{title:"Pattern",body:"Abstract only behavior that must vary."}] },
  "meeting-immutable-values": { intro: "Requested intent and an accepted reservation are different immutable facts.", items: [{title:"TimeSlot",body:"Validates start < end and owns overlap."},{title:"MeetingRequest",body:"Carries title, organizer, attendees, equipment, and slot."},{title:"Meeting",body:"Adds the accepted meeting and room IDs."},{title:"ScheduleResult",body:"Returns an explicit status and optional meeting."},{title:"Defensive copy",body:"Set.copyOf prevents equipment changes after construction."}] },
  "meeting-half-open": { intro: "A half-open interval includes its start and excludes its end: [start, end).", items: [{title:"Touching",body:"[09:00,10:00) and [10:00,10:30) do not overlap."},{title:"Partial",body:"[09:30,10:30) overlaps [09:00,10:00)."},{title:"Contained",body:"[09:15,09:45) overlaps the containing meeting."},{title:"Formula",body:"a.start < b.end AND b.start < a.end."}], conclusion:"Strict < comparisons are what allow back-to-back meetings." },
  "meeting-room-design": { intro: "Room owns the facts and rules needed to protect one calendar.", items: [{title:"State",body:"ID, name, capacity, equipment, and ordered meetings."},{title:"Suitability",body:"canHost checks capacity and equipment."},{title:"Availability",body:"isAvailable checks the two relevant neighbours."},{title:"Mutation",body:"reserve and remove preserve the schedule invariant."},{title:"Safe read",body:"meetings returns an immutable snapshot."}] },
  "meeting-invariant": { intro: "An invariant is a promise that remains true after every public operation.", items: [{title:"Suitable",body:"Every stored meeting fits this Room."},{title:"Non-overlapping",body:"No two stored TimeSlots overlap."},{title:"Unique starts",body:"Meetings with equal starts would overlap and cannot coexist."},{title:"Private map",body:"Callers never receive the mutable TreeMap."}], conclusion:"reserve checks the promise before inserting; remove preserves it." },
  "meeting-complexity": { intro: "An ordered schedule trades a little complexity for fast neighbour lookup.", items: [{title:"Availability",body:"floorEntry and ceilingEntry are O(log M)."},{title:"Room selection",body:"Checking R rooms costs O(R log M)."},{title:"Insertion",body:"An accepted reservation costs O(log M)."},{title:"Alternative",body:"A list scan is simpler and reasonable when each room has few meetings."}] },
  "meeting-strategy-design": { intro: "Strategy owns only the replaceable choice rule.", items: [{title:"Filter 1",body:"Enough capacity."},{title:"Filter 2",body:"All required equipment."},{title:"Filter 3",body:"Available for the full slot."},{title:"Choose",body:"Lowest capacity, then lowest room ID."},{title:"Boundary",body:"Strategy returns a Room; it never reserves or creates IDs."}] },
  "meeting-scheduler-design": { intro: "MeetingScheduler coordinates the use case without calculating overlaps itself.", items: [{title:"State",body:"Immutable rooms, room index, meeting index, strategy, and ID sequence."},{title:"schedule",body:"Select, construct, reserve, advance ID, index, return."},{title:"cancel",body:"Find, verify organizer, remove from Room, remove index."},{title:"Safe read",body:"meetingsForRoom delegates to the Room snapshot."}], conclusion:"IDs advance only after a reservation succeeds." },
  "meeting-code-map": { intro: "The Java types follow the responsibility boundaries from design.", items: [{title:"Values",body:"Validate stable request and reservation facts."},{title:"Room",body:"Own suitability, neighbours, and schedule mutation."},{title:"Strategy",body:"Filter and compare candidate rooms."},{title:"Scheduler",body:"Coordinate IDs, indexes, scheduling, and cancellation."}] },
  "meeting-enums": { intro: "Named outcomes make expected failures explicit.", items: [{title:"Equipment",body:"PROJECTOR, WHITEBOARD, VIDEO."},{title:"ScheduleStatus",body:"SCHEDULED or NO_ROOM_AVAILABLE."},{title:"CancellationStatus",body:"CANCELED, MEETING_NOT_FOUND, or NOT_ORGANIZER."}] },
  "meeting-demo": { intro: "A useful demo proves boundaries, not just the happy path.", items: [{title:"Back-to-back",body:"A 10:00 request can reuse a room ending at 10:00."},{title:"Fallback",body:"A busy smaller room lets the next qualified room win."},{title:"Full rejection",body:"No candidate leaves schedules and IDs unchanged."},{title:"Cancellation",body:"Wrong owner fails; correct owner frees the room for reuse."}] },
  "meeting-success-trace": { intro: "Trace [10:00,10:30) beside Focus’s [09:00,10:00).", items: [{title:"Predecessor",body:"Its end equals the requested start, so strict overlap is false."},{title:"Successor",body:"No later neighbour crosses the requested end."},{title:"Selection",body:"Focus is suitable and the smallest available room."},{title:"Commit",body:"Room reserves first; then Scheduler advances ID and indexes Meeting."}] },
  "meeting-rejection-proof": { intro: "Every expected rejection returns before the state it protects can change.", items: [{title:"No room",body:"No schedule, index, or ID sequence changes."},{title:"Wrong organizer",body:"The meeting remains indexed and reserved."},{title:"Unknown meeting",body:"No Room lookup or removal occurs."}], conclusion:"The next accepted request still receives the next accepted ID." },
};

const timeSlotCode = `public record TimeSlot(LocalDateTime start, LocalDateTime end) {
    public TimeSlot {
        Objects.requireNonNull(start);
        Objects.requireNonNull(end);
        if (!start.isBefore(end)) {
            throw new IllegalArgumentException("Start must be before end");
        }
    }

    public boolean overlaps(TimeSlot other) {
        Objects.requireNonNull(other);
        return start.isBefore(other.end())
                && other.start().isBefore(end);
    }
}`;

export function MeetingRoomFocusSlide({ id }: { id: string }) {
  if (id === "meeting-orientation") return <Image src="/images/meeting-room-scheduler-overview.png" alt="A request passes capacity, equipment, and time checks before the smallest qualified room is selected" width={1536} height={1024} className="h-full max-h-[29rem] w-full rounded-xl border border-[var(--line)] object-contain" priority unoptimized />;
  if (id === "meeting-framework") return <FocusFrameworkRoadmap />;
  if (id === "meeting-interview") return <InterviewDynamicsGuide timing={[{label:"Requirements",minutes:"5 min"},{label:"Entities",minutes:"3 min"},{label:"Class design",minutes:"12 min"},{label:"Code",minutes:"15 min"},{label:"Extensions",minutes:"5 min"}]} speaking={["Define available with a concrete touching-boundary example.","State the capacity/ID tie-break before showing Strategy.","Say that the first implementation is sequential and in memory."]} signals={[{id:"smallest",signal:"What does smallest mean?",response:"Clarify lowest capacity, with room ID as the deterministic tie-break."},{id:"conflict",signal:"Do these meetings conflict?",response:"Write the half-open formula and test touching boundaries."},{id:"scale",signal:"How does this scale?",response:"Explain TreeMap neighbour lookup, then property indexes as an extension."}]} />;
  if (id === "meeting-dialogue") return <InterviewDialogueExample turns={[{speaker:"Candidate",text:"Does [09:00,10:00) conflict with a meeting starting exactly at 10:00?"},{speaker:"Interviewer",text:"No. Treat intervals as start-inclusive and end-exclusive."},{speaker:"Candidate",text:"Then overlap uses two strict comparisons, so touching boundaries are allowed."}]} />;
  if (id === "meeting-orientation-check" || id === "meeting-questions") return <PredictionChecklist prompt={id.endsWith("questions") ? "Select the questions that change the implementation." : "What must be clarified before naming classes?"} items={[{id:"actions",label:"Schedule and cancellation actions",correct:true,feedback:"These define the public use cases."},{id:"fit",label:"Capacity and equipment suitability",correct:true,feedback:"These rules belong in Room."},{id:"boundary",label:"Whether touching intervals conflict",correct:true,feedback:"This determines the overlap formula."},{id:"winner",label:"How several qualified rooms are ordered",correct:true,feedback:"A deterministic policy is testable."},{id:"cancel",label:"Who may cancel and what rejection changes",correct:true,feedback:"Ownership and invariants must be explicit."},{id:"scope",label:"Sequential or concurrent callers",correct:true,feedback:"This decides whether locking is core or an extension."},{id:"color",label:"Calendar event color",correct:false,feedback:"Presentation does not change scheduling correctness."}]} success="You found the facts that determine the model and its invariants." />;
  if (id === "meeting-spec") return <FocusSpec compact requirements={["Rooms have unique ID, name, capacity, and equipment.","Requests contain title, organizer, attendees, equipment, and a valid slot.","Slots are [start,end); touching meetings are allowed.","A room must satisfy capacity, equipment, and availability.","Choose lowest capacity, then lowest room ID.","No-room rejection changes nothing.","Only the organizer may cancel a known meeting.","Successful cancellation frees the exact room and slot."]} outOfScope={["Recurrence","Attendee calendars","Time-zone conversion","Setup buffers","Persistence","Concurrent callers","Notifications","In-place rescheduling"]} />;
  if (id === "meeting-types") return <PredictionChecklist prompt="Which candidates deserve a class, record, or interface?" items={[{id:"slot",label:"TimeSlot",correct:true,feedback:"It validates and compares interval boundaries."},{id:"request",label:"MeetingRequest",correct:true,feedback:"It carries one immutable scheduling intent."},{id:"meeting",label:"Meeting",correct:true,feedback:"It records an accepted reservation."},{id:"room",label:"Room",correct:true,feedback:"It owns suitability and one ordered schedule."},{id:"scheduler",label:"MeetingScheduler",correct:true,feedback:"It coordinates IDs, selection, indexing, and cancellation."},{id:"strategy",label:"RoomSelectionStrategy",correct:true,feedback:"The confirmed selection policy is replaceable."},{id:"calendar",label:"Separate Calendar",correct:false,feedback:"Room already owns the only calendar in scope."},{id:"attendee",label:"Attendee profile",correct:false,feedback:"Only attendeeCount is required."}]} success="The types now match the confirmed responsibilities." />;
  if (id === "meeting-values") return <ClassificationChallenge instruction="Choose the smallest representation." categories={[{id:"enum",label:"Enum"},{id:"value",label:"Immutable value"},{id:"field",label:"Field"},{id:"private",label:"Private state"},{id:"omit",label:"Leave out"}]} items={[{id:"status",label:"Equipment and result statuses",answer:"enum",feedback:"They are small closed choices."},{id:"result",label:"ScheduleResult",answer:"value",feedback:"It safely carries one operation result."},{id:"ids",label:"Organizer ID and attendee count",answer:"field",feedback:"They have no independent behavior."},{id:"tree",label:"Ordered schedule",answer:"private",feedback:"It is Room implementation state."},{id:"people",label:"Organizer and Attendee classes",answer:"omit",feedback:"No confirmed profile behavior needs them."}]} success="Every concept has the smallest useful shape." />;
  if (id === "meeting-ownership") return <ClassificationChallenge instruction="Give each rule to the type with the information needed to check it." categories={[{id:"slot",label:"TimeSlot"},{id:"room",label:"Room"},{id:"strategy",label:"Strategy"},{id:"scheduler",label:"Scheduler"}]} items={[{id:"overlap",label:"Validate and compare intervals",answer:"slot",feedback:"TimeSlot owns both boundaries."},{id:"fit",label:"Check capacity, equipment, and neighbours",answer:"room",feedback:"Room owns fixed properties and its schedule."},{id:"choose",label:"Compare qualified rooms",answer:"strategy",feedback:"Strategy owns the replaceable ordering."},{id:"ids",label:"Create IDs and index accepted meetings",answer:"scheduler",feedback:"Scheduler owns the workflow indexes."},{id:"cancel",label:"Check cancellation organizer",answer:"scheduler",feedback:"Scheduler looks up the accepted Meeting first."}]} success="Each rule is beside the information it needs." />;
  if (id === "meeting-entity-flow") return <OrderQuestion prompt="Order one accepted scheduling flow." items={[{id:"reserve",label:"Room reserves the Meeting"},{id:"request",label:"Organizer submits MeetingRequest"},{id:"return",label:"Scheduler indexes and returns the result"},{id:"check",label:"Room checks suitability and neighbours"},{id:"select",label:"Strategy returns the smallest qualified Room"},{id:"meeting",label:"Scheduler creates the Meeting"},{id:"ask",label:"Scheduler asks Strategy to select"},{id:"scan",label:"Strategy asks each Room whether it can host"}]} correctOrder={["request","ask","scan","check","select","meeting","reserve","return"]} explanation="Selection is read-only. The chosen Room protects its own schedule before the Scheduler indexes success." />;
  if (id === "meeting-principles") return <ClassificationChallenge instruction="Match each failure to the principle that prevents it." categories={[{id:"enc",label:"Encapsulation"},{id:"srp",label:"Single responsibility"},{id:"imm",label:"Immutability"},{id:"open",label:"Open/closed"},{id:"comp",label:"Composition"}]} items={[{id:"map",label:"Caller edits a Room schedule",answer:"enc",feedback:"Private state and guarded methods protect the invariant."},{id:"calc",label:"Scheduler calculates interval overlap",answer:"srp",feedback:"TimeSlot and Room already own that information."},{id:"edit",label:"Accepted meeting facts change",answer:"imm",feedback:"Immutable values preserve the reservation."},{id:"policy",label:"New policy rewrites Scheduler",answer:"open",feedback:"A Strategy interface localizes variation."},{id:"inherits",label:"Scheduler inherits from Room",answer:"comp",feedback:"It has rooms; it is not a room."}]} callout="Principles protect concrete scheduling failures; they are not decorations." success="You connected each principle to the failure it prevents." />;
  if (id === "meeting-overlap-practice" || id === "meeting-timeslot-predict") return <ChoiceQuestion prompt="Does [09:00,10:00) overlap [10:00,10:30)?" choices={[{id:"no",label:"No—boundaries only touch",correct:true,feedback:"09:00 < 10:30 is true, but 10:00 < 10:00 is false."},{id:"yes",label:"Yes—10:00 appears in both",correct:false,feedback:"The first interval excludes its end, so 10:00 belongs only to the second."},{id:"invalid",label:"The second slot is invalid",correct:false,feedback:"Its start is before its end."}]} />;
  if (id === "meeting-neighbours" || id === "meeting-room-availability-predict") return <ChoiceQuestion prompt="For requested [10:00,10:30), which stored entries can possibly overlap?" choices={[{id:"two",label:"floorEntry(10:00) and ceilingEntry(10:00)",correct:true,feedback:"Any more distant meeting is separated by one of these neighbours."},{id:"all",label:"Every meeting in the TreeMap",correct:false,feedback:"The invariant lets ordered neighbours prove the answer."},{id:"floor",label:"Only floorEntry(10:00)",correct:false,feedback:"A successor can start before the requested slot ends."}]} />;
  if (id === "meeting-schedule-order") return <OrderQuestion prompt="Order a safe scheduling request." items={[{id:"index",label:"Index the accepted Meeting"},{id:"select",label:"Select a qualified Room"},{id:"validate",label:"Validate MeetingRequest"},{id:"advance",label:"Advance the accepted ID"},{id:"construct",label:"Construct the Meeting with a tentative ID"},{id:"reserve",label:"Ask Room to reserve"},{id:"return",label:"Return ScheduleResult"}]} correctOrder={["validate","select","construct","reserve","advance","index","return"]} explanation="Reservation must succeed before the sequence and accepted-meeting index change." />;
  if (id === "meeting-code-concepts") return <TabbedConceptView tabs={[{id:"records",label:"Records",title:"Records hold stable values",body:"Compact constructors validate TimeSlot and request facts once."},{id:"interval",label:"Intervals",title:"Strict comparisons implement [start,end)",body:"Touching meetings remain legal without a special case."},{id:"tree",label:"TreeMap",title:"Ordering exposes two relevant neighbours",body:"floorEntry and ceilingEntry cost O(log M)."},{id:"copy",label:"Copies",title:"Immutable collections protect internals",body:"Set.copyOf and List.copyOf prevent external mutation."},{id:"results",label:"Results",title:"Named statuses represent expected rejection",body:"No-room and cancellation failures are not exceptions."}]} />;
  if (id === "meeting-enums") return <TabbedCodeView label="Fixed values and named outcomes" tabs={[{id:"equipment",label:"Equipment",code:`public enum Equipment {\n    PROJECTOR,\n    WHITEBOARD,\n    VIDEO\n}`},{id:"schedule",label:"Schedule",code:`public enum ScheduleStatus {\n    SCHEDULED,\n    NO_ROOM_AVAILABLE\n}`},{id:"cancel",label:"Cancellation",code:`public enum CancellationStatus {\n    CANCELED,\n    MEETING_NOT_FOUND,\n    NOT_ORGANIZER\n}`}]} />;
  if (id === "meeting-records") return <TabbedCodeView label="Immutable meeting values" tabs={[{id:"slot",label:"TimeSlot",code:timeSlotCode},{id:"request",label:"MeetingRequest",code:`public record MeetingRequest(String title, String organizerId, TimeSlot slot, int attendeeCount, Set<Equipment> requiredEquipment) {\n    public MeetingRequest {\n        if (title == null || title.isBlank() || organizerId == null || organizerId.isBlank() || slot == null || attendeeCount < 1) throw new IllegalArgumentException();\n        requiredEquipment = Set.copyOf(requiredEquipment);\n    }\n}`},{id:"meeting",label:"Meeting",code:`public record Meeting(String id, String title, String organizerId, String roomId, TimeSlot slot, int attendeeCount, Set<Equipment> requiredEquipment) {\n    public Meeting {\n        requiredEquipment = Set.copyOf(requiredEquipment);\n    }\n}`},{id:"result",label:"Result",code:`public record ScheduleResult(ScheduleStatus status, Optional<Meeting> meeting) {\n    public ScheduleResult {\n        if (status == null || meeting == null) throw new IllegalArgumentException("Result fields are required");\n    }\n    public static ScheduleResult accepted(Meeting meeting) {\n        return new ScheduleResult(ScheduleStatus.SCHEDULED, Optional.of(meeting));\n    }\n    public static ScheduleResult rejected() {\n        return new ScheduleResult(ScheduleStatus.NO_ROOM_AVAILABLE, Optional.empty());\n    }\n}`}]} />;
  if (id === "meeting-timeslot-code") return <TabbedCodeView label="Complete TimeSlot" tabs={[{id:"slot",label:"TimeSlot",code:timeSlotCode}]} />;
  if (id === "meeting-room-setup-code") return <TabbedCodeView label="Room construction and suitability" tabs={[{id:"construct",label:"Construction",code:`public Room(String id, String name, int capacity, Set<Equipment> equipment) {\n    if (id == null || id.isBlank() || name == null || name.isBlank() || capacity < 1) throw new IllegalArgumentException();\n    this.id = id; this.name = name; this.capacity = capacity; this.equipment = Set.copyOf(equipment);\n}`},{id:"host",label:"canHost",code:`public boolean canHost(MeetingRequest request) {\n    return capacity >= request.attendeeCount()\n            && equipment.containsAll(request.requiredEquipment())\n            && isAvailable(request.slot());\n}`}]} />;
  if (id === "meeting-room-availability-code") return <TabbedCodeView label="Room protects its ordered schedule" tabs={[{id:"available",label:"Availability",code:`public boolean isAvailable(TimeSlot requested) {\n    Map.Entry<LocalDateTime, Meeting> before = schedule.floorEntry(requested.start());\n    if (before != null && before.getValue().slot().overlaps(requested)) return false;\n    Map.Entry<LocalDateTime, Meeting> after = schedule.ceilingEntry(requested.start());\n    return after == null || !after.getValue().slot().overlaps(requested);\n}`},{id:"reserve",label:"Reserve",code:`public boolean reserve(Meeting meeting) {\n    if (!id.equals(meeting.roomId())\n            || capacity < meeting.attendeeCount()\n            || !equipment.containsAll(meeting.requiredEquipment())\n            || !isAvailable(meeting.slot())) {\n        return false;\n    }\n    schedule.put(meeting.slot().start(), meeting);\n    return true;\n}`},{id:"remove",label:"Remove & read",code:`public boolean remove(Meeting meeting) {\n    if (meeting == null || !id.equals(meeting.roomId())) return false;\n    return schedule.remove(meeting.slot().start(), meeting);\n}\n\npublic List<Meeting> meetings() {\n    return List.copyOf(schedule.values());\n}`}]} />;
  if (id === "meeting-selection-predict") return <ChoiceQuestion prompt="Focus (4) is busy, Cedar (6) is free, and Atlas (6) is free. Which room wins?" choices={[{id:"cedar",label:"Lower room ID among capacity 6",correct:true,feedback:"After suitability and availability, capacity ties are broken by room ID."},{id:"focus",label:"Focus because it is smallest",correct:false,feedback:"A busy room is filtered out before comparison."},{id:"either",label:"Either free room",correct:false,feedback:"The confirmed tie-break makes the result deterministic."}]} />;
  if (id === "meeting-strategy-code") return <TabbedCodeView label="Complete selection policy" tabs={[{id:"strategy",label:"Strategy",code:`public Optional<Room> select(List<Room> rooms, MeetingRequest request) {\n    return rooms.stream()\n            .filter(room -> room.canHost(request))\n            .min(Comparator.comparingInt(Room::capacity)\n                    .thenComparing(Room::id));\n}`}]} />;
  if (id === "meeting-scheduler-predict") return <PredictionChecklist prompt="Which rules belong in MeetingScheduler?" items={[{id:"select",label:"Delegate room choice to Strategy",correct:true,feedback:"The policy is replaceable."},{id:"reserve",label:"Reserve before indexing success",correct:true,feedback:"Rejected reservation must change nothing."},{id:"owner",label:"Check cancellation organizer",correct:true,feedback:"Scheduler owns accepted meeting lookup."},{id:"overlap",label:"Calculate interval overlap",correct:false,feedback:"TimeSlot and Room own interval rules."},{id:"map",label:"Expose the mutable Room schedule",correct:false,feedback:"That would bypass Room's invariant."}]} success="The Scheduler coordinates without taking over Room rules." />;
  if (id === "meeting-scheduler-code") return <TabbedCodeView label="MeetingScheduler by responsibility" tabs={[{id:"schedule",label:"schedule",code:`public ScheduleResult schedule(MeetingRequest request) {\n    if (request == null) throw new IllegalArgumentException("Request is required");\n    Optional<Room> selected = strategy.select(rooms, request);\n    if (selected.isEmpty()) return ScheduleResult.rejected();\n    Room room = selected.get();\n    String id = "M" + nextMeetingNumber;\n    Meeting meeting = new Meeting(id, request.title(), request.organizerId(), room.id(), request.slot(), request.attendeeCount(), request.requiredEquipment());\n    if (!room.reserve(meeting)) return ScheduleResult.rejected();\n    nextMeetingNumber++;\n    meetingsById.put(id, meeting);\n    return ScheduleResult.accepted(meeting);\n}`},{id:"cancel",label:"cancel",code:`public CancellationStatus cancel(String meetingId, String organizerId) {\n    Meeting meeting = meetingsById.get(meetingId);\n    if (meeting == null) return CancellationStatus.MEETING_NOT_FOUND;\n    if (!meeting.organizerId().equals(organizerId)) return CancellationStatus.NOT_ORGANIZER;\n    Room room = roomsById.get(meeting.roomId());\n    if (!room.remove(meeting)) throw new IllegalStateException("Meeting index and room disagree");\n    meetingsById.remove(meetingId);\n    return CancellationStatus.CANCELED;\n}`},{id:"read",label:"safe read",code:`public List<Meeting> meetingsForRoom(String roomId) {\n    Room room = roomsById.get(roomId);\n    return room == null ? List.of() : room.meetings();\n}`}]} />;
  if (id === "meeting-blueprint") return <MeetingBlueprint />;
  if (id === "meeting-simulator") return <MeetingRoomSchedulerSimulator compact />;
  if (id === "meeting-rule-extensions") return <TabbedConceptView tabs={[{id:"buffer",label:"Buffers",title:"Expand the conflict interval",body:"TimeSlot can create a buffered comparison slot while Meeting keeps visible times."},{id:"repeat",label:"Recurrence",title:"Validate every occurrence before mutation",body:"A recurrence rule expands into a bounded set of TimeSlots."},{id:"people",label:"Attendees",title:"Add a separate calendar owner",body:"Room and attendee availability remain different responsibilities."},{id:"scale",label:"Scale",title:"Filter fixed properties before schedules",body:"Indexes reduce candidate rooms while keeping the same deterministic tie-break."}]} />;
  if (id === "meeting-concurrency-close") return <ChoiceQuestion prompt="How should you explain simultaneous requests in an interview?" choices={[{id:"boundary",label:"Protect Room check-and-insert; use shared transactions across servers",correct:true,feedback:"This identifies the race, one-process lock boundary, and production authority."},{id:"safe",label:"TreeMap already makes scheduling thread-safe",correct:false,feedback:"Ordering does not make check-then-insert atomic."},{id:"singleton",label:"Make MeetingScheduler a Singleton",correct:false,feedback:"Singleton neither protects transitions nor coordinates several servers."}]} />;
  return passive[id] ? <PassiveLearningCards {...passive[id]} /> : <PassiveLearningCards intro="Connect this step to the confirmed invariant before moving into code." items={[{title:"Owner",body:"Put each rule beside the state it needs."},{title:"Boundary",body:"Validate before changing accepted state."},{title:"Result",body:"Keep success and rejection observable and deterministic."}]} />;
}

function MeetingBlueprint() {
  return <Tabs defaultValue="values" className="flex h-full min-h-0 flex-col"><TabsList className="grid w-full grid-cols-5">{meetingRoomClassDiagrams.map((tab) => <TabsTrigger key={tab.id} value={tab.id} className="text-[9px]">{tab.label}</TabsTrigger>)}</TabsList>{meetingRoomClassDiagrams.map((tab) => <TabsContent key={tab.id} value={tab.id} className="mt-2 min-h-0 flex-1"><div className="grid h-full min-h-0 grid-rows-[minmax(0,1fr)_auto] overflow-hidden rounded-xl border border-[var(--line)] bg-white"><div className="min-h-0 overflow-hidden bg-[#fbf7ef]"><Image src={tab.image} alt={tab.alt} width={tab.width ?? 1536} height={tab.height ?? 1024} className="h-full w-full object-contain" loading="eager" unoptimized /></div><div className="grid gap-1 border-t p-2 text-[9px] leading-4 sm:grid-cols-2"><p><strong>Read it: </strong>{tab.reading}</p><p><strong>Principle: </strong>{tab.principle}</p></div></div></TabsContent>)}</Tabs>;
}
