// Generated by npm run images:generate. Do not edit by hand.
// Original PNGs are retained; all URLs are unprefixed public paths.

export type ImageVariant = {
  src: string;
  width: number;
  height: number;
  bytes: number;
  sha256: string;
};

export type ImageVariantDefinition = {
  width: number;
  height: number;
  bytes: number;
  sha256: string;
  candidates: readonly ImageVariant[];
};

export const imageVariantSettings = {
  "format": "webp",
  "widths": [
    384,
    640,
    768,
    1024,
    1360
  ],
  "includeOriginalWidth": true,
  "withoutEnlargement": true,
  "quality": 85,
  "effort": 6,
  "kernel": "lanczos3",
  "sharp": "0.35.3",
  "vips": "8.18.3",
  "webp": "1.6.0"
} as const;

export const imageVariants: Readonly<Record<string, ImageVariantDefinition>> = {
  "/images/components/kafka/kafka-activity-analytics.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2560843,
    "sha256": "5e183ac39a225042b69bcc6ad72a6878161d369cda122e3dc147f0c280c5a801",
    "candidates": [
      {
        "src": "/images/optimized/components/kafka/kafka-activity-analytics-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 22610,
        "sha256": "564f08be21511344fc4807c592119100ad379dd3fdeb7c23728fb11a836dabf1"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-activity-analytics-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 49416,
        "sha256": "97338df0e42d823c57f2ca71cf5f553ad5212f26d5eeed4cb248cff0e74ede22"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-activity-analytics-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 65176,
        "sha256": "9dcaa5d8bc23a1fdc1bb93909e3d5bd6e301650c73f535b77384a8564002daae"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-activity-analytics-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 99042,
        "sha256": "b1937fc7d4986e070efb6a684bf312e5cc8f1cafa0b17259ee49ef8d3fe4b19d"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-activity-analytics-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 154238,
        "sha256": "9f0d2adffd019a4d21f7f1e3b0ca4de24c55c0dba1ff86d3bcc71b9eb152597c"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-activity-analytics-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 189940,
        "sha256": "e142f5a9db58f660b9e56fb91276d43d2e86b67ed7156062875e1419a440592e"
      }
    ]
  },
  "/images/components/kafka/kafka-cdc.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2867630,
    "sha256": "4c70e512d6c2927057e249469450215e2a5f30a7de2e9d94f280c00b9de48053",
    "candidates": [
      {
        "src": "/images/optimized/components/kafka/kafka-cdc-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 17360,
        "sha256": "065de131b8d6b06e28da6038fa29c4651a8ec159336fc502c9e00bcc5343c06a"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-cdc-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 38170,
        "sha256": "3dbb318ce3fdf5fb3d2062a1646f03b8bff44a8c7e81890795a615784912f073"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-cdc-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 51262,
        "sha256": "47a2cbe0af1dec77e0daadbc7a8c103e0c34d719a760dc6c214591757075ba2c"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-cdc-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 89280,
        "sha256": "06bd675190828353fd746a46849b3e89dfdfe2c3c4d4a67c94899d2af42f9090"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-cdc-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 158266,
        "sha256": "5991d71aed673bcfff56e00e6e56603908d2b3e251d55d9c0c66b3494e45dc0e"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-cdc-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 210064,
        "sha256": "9defe045d9b34f3e11d453e52bc8e3baf4c9987947465aa1b9dd48708649831c"
      }
    ]
  },
  "/images/components/kafka/kafka-consumer-groups.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2640996,
    "sha256": "99e3412d989e017eb02c5ac1ed35d5d1e67ff5667678f04e472433ab9a031eb6",
    "candidates": [
      {
        "src": "/images/optimized/components/kafka/kafka-consumer-groups-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 17872,
        "sha256": "b22f6bfc33a5bc94155d9b3a414d9ad62fe1d81a15dc94c9efe3e92fcc22ff93"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-consumer-groups-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 38854,
        "sha256": "6a7c6d5b2d008953dec7d4afd2e65a1efaed863b54e2f937b0f722be5bebfec2"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-consumer-groups-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 51974,
        "sha256": "d048b6d5180437c0ff92b5c49dd593a03dd5a8b248b80c0fe690371c679827a0"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-consumer-groups-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 84738,
        "sha256": "93dc11af773878917d09918dc8daab9f6ee29029320d7701085ed7106389ed7a"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-consumer-groups-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 138636,
        "sha256": "1c60b41ba701ef1b5e812e63a0966b9eb98684fee8c3a07102cc09fb8d912c84"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-consumer-groups-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 172392,
        "sha256": "0c3c03081297da5669dabb1bddd08a3c9f0419ada0f004abc97c5a6cc41b9ea7"
      }
    ]
  },
  "/images/components/kafka/kafka-order-fanout.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2667577,
    "sha256": "5aa1d610ef73ca9965ce9ab0a558cb21102477864cbe851010e6fb0ae93e09a6",
    "candidates": [
      {
        "src": "/images/optimized/components/kafka/kafka-order-fanout-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 16366,
        "sha256": "59ef91914dc2b87ee4267064d1b1485204f343a5deb1b02032a03ffbf63d2e92"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-order-fanout-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 35184,
        "sha256": "979ace7553efb996c8b120531318a9615ab60da0072799dc66b4233e4e6ceb3d"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-order-fanout-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 46414,
        "sha256": "7ee711d5bb26729fe050764c1ccc3f2396ec856c7eece164b6caa6381db2ca58"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-order-fanout-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 76096,
        "sha256": "a97a7a9f0c59cd6f007d85435cba8e28381e57e8174edee52830e288cddef714"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-order-fanout-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 127086,
        "sha256": "1a958ec39ea02df43bfb292d6533ca5999060a7a7ad240eeca99f5e56845b68d"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-order-fanout-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 163348,
        "sha256": "14576d707fd0edb5e7d228e50444677b299008c98d157290bd61ef49cdab6010"
      }
    ]
  },
  "/images/components/kafka/kafka-overview.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 1957829,
    "sha256": "07b10a1474f26676ee5beea1ed2fde99d0c20c24086297f8c7d5c4f3edd02196",
    "candidates": [
      {
        "src": "/images/optimized/components/kafka/kafka-overview-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 13008,
        "sha256": "f3efe16d5e533bf90cbfcf3f79564f95a8b03c012723e6af0896844ada4bf627"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-overview-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 27572,
        "sha256": "9d6292c862a0581800d600b7a4de04d5774aa65b5bb49cb853f1a3d34e55cfb2"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-overview-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 35186,
        "sha256": "6979320c6f4ab2996b680e07fa1bd180e6a286708deca00d6ddbf7905f4ff48d"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-overview-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 53346,
        "sha256": "af95b44e54ed684d840510da3d6da30b535304c45ef87376070fa340e030d66c"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-overview-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 80320,
        "sha256": "46a283499de0645aafd0affbb0b88cbc6c779e1b3d104d85e689c8f6ea5da924"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-overview-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 97114,
        "sha256": "6790945a9e8ae7d9e73a888fec966350b49dbbbec590527d7200abd890f554cc"
      }
    ]
  },
  "/images/components/kafka/kafka-partitions.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2051608,
    "sha256": "d809f9a4895d9edc547426dfa279799186273123f38b90bec9e6635fba7e36c9",
    "candidates": [
      {
        "src": "/images/optimized/components/kafka/kafka-partitions-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 17206,
        "sha256": "ce89855df48c72eeb73b780dd89400e8ae51d1428f726486831900f5258c1ac5"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-partitions-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 36532,
        "sha256": "e42163d892563f751297bd6c7a8321409bfe1571d64b203473d6dbbbb9b13499"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-partitions-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 47738,
        "sha256": "97deb7004b99ebf22b431fff7f92201b9d18b59377f18679bbdc22661ba5509c"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-partitions-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 72198,
        "sha256": "1cfe044070064599ec19cf3a029aa52499d8f45ff6675244c8632ee7db973d74"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-partitions-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 110234,
        "sha256": "e09414a968c9f1088e0f72067fd1cb5063ce6d717f0f11f78f258581d78d8f66"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-partitions-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 131182,
        "sha256": "3170d590bef8589731b0b4b2501d9024718e2237e5ac7aac0fa90dc670185d54"
      }
    ]
  },
  "/images/components/kafka/kafka-replication.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2491424,
    "sha256": "fe970477ed49c00656972bb49a0e6a9d486d128537b9adb6e50b637b086fd131",
    "candidates": [
      {
        "src": "/images/optimized/components/kafka/kafka-replication-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 14400,
        "sha256": "dc18bef972f41bc3b038cf3823b48b9d58efb7f46c9c43535b7ed7ca8ef02f31"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-replication-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 32176,
        "sha256": "e7e27b16fb156336307e4734190246903e064a01981dd26b6113c80ed32d2a70"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-replication-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 42654,
        "sha256": "8d4c2e55b21e387f73baa8a5911e076c89010bf76445dd9dd2652b10e421f274"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-replication-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 66948,
        "sha256": "fe6d30020c6a2113e44dbcf0f35e7e6420951a28d4106ac0e0cad178fc3d3d14"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-replication-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 108138,
        "sha256": "164de1e07d58e40d76ac1ec9acdd1dce1b0b19e899275c046cb1e2d0ca552518"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-replication-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 137596,
        "sha256": "d5dc53a790c8509abd0a0cb1d98281c32b63dd805ac9cc3cf7cbc252420394f6"
      }
    ]
  },
  "/images/components/kafka/kafka-traffic-spike.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2503322,
    "sha256": "ceba536ed9a6a7598d014894d652e905feab52e848e3337dafeea63bfd9439f4",
    "candidates": [
      {
        "src": "/images/optimized/components/kafka/kafka-traffic-spike-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 20108,
        "sha256": "a1569d57da6c935df4835cc434207aa39583678cddca4081b3937ea1b88f4e5d"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-traffic-spike-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 42488,
        "sha256": "01d70528021ee1707ff498dafe444d186a2469b4b2feaf9e4534c0afcc1cf8d3"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-traffic-spike-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 56862,
        "sha256": "8a1a81d8151193379f2e4a6e457e0a40dae4ed0f21a5bd24c0b81e14c38bc5dd"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-traffic-spike-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 86372,
        "sha256": "401222d91d79b1f2dbfe3c82e48af3143f36794f0572aeaaeea4f1b308e18dc5"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-traffic-spike-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 134222,
        "sha256": "008fb58b82279dd1f550495d160b4343ef0a9763aae3ecb44e0e7cc403132924"
      },
      {
        "src": "/images/optimized/components/kafka/kafka-traffic-spike-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 169722,
        "sha256": "6c98da988999793e1d8d24e8d5f7a07924fe68d0dc224ce1c43451fd41c189b2"
      }
    ]
  },
  "/images/elevator-entity-flow.png": {
    "width": 1774,
    "height": 887,
    "bytes": 2124601,
    "sha256": "3999f6efdc3ab27b8c32c59c130fe92c89eb20a02ad26a3049a224d684cf125f",
    "candidates": [
      {
        "src": "/images/optimized/elevator-entity-flow-384.webp",
        "width": 384,
        "height": 192,
        "bytes": 8182,
        "sha256": "07b648a6ea8da6f84d1a05b538c3383e7787215efc1d0d7e5939df90dd3207ca"
      },
      {
        "src": "/images/optimized/elevator-entity-flow-640.webp",
        "width": 640,
        "height": 320,
        "bytes": 18260,
        "sha256": "a2dbdf1d7f00d825f4b5677a3923174f0e8a965a0be0066caf17196328d49df8"
      },
      {
        "src": "/images/optimized/elevator-entity-flow-768.webp",
        "width": 768,
        "height": 384,
        "bytes": 24688,
        "sha256": "2987e1c0ef6957c7719695d991f9d590860d5ac01391ffa883e77b24de88d698"
      },
      {
        "src": "/images/optimized/elevator-entity-flow-1024.webp",
        "width": 1024,
        "height": 512,
        "bytes": 38638,
        "sha256": "27bfca6e911e656920b1291260c417cb114cafb9ffb17f662b1f5d9fd526cc9a"
      },
      {
        "src": "/images/optimized/elevator-entity-flow-1360.webp",
        "width": 1360,
        "height": 680,
        "bytes": 62868,
        "sha256": "e143ee04b736e564070ab7a658404e58466d7e264736b3f442699d7b881c7241"
      },
      {
        "src": "/images/optimized/elevator-entity-flow-1774.webp",
        "width": 1774,
        "height": 887,
        "bytes": 96606,
        "sha256": "9345d62dd71401cdb57b77f60e0358babf9f0b9666d16b635fedb1f5c7b2d796"
      }
    ]
  },
  "/images/elevator-system-overview.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2988430,
    "sha256": "9cb336a4d3514a22ca2df2dfa88b54f79159bdf69883a97d4335bfeea9c41275",
    "candidates": [
      {
        "src": "/images/optimized/elevator-system-overview-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 13140,
        "sha256": "dafb2f253b506392f96971585bcb2d05f8ce521b93b05d158daa01336f9d59c5"
      },
      {
        "src": "/images/optimized/elevator-system-overview-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 35550,
        "sha256": "54129d8470760b4a052232cc2e7c8d112af9872ddc2bc4006f340dc96202156e"
      },
      {
        "src": "/images/optimized/elevator-system-overview-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 51512,
        "sha256": "c374b1aa6f85bd20d6d0d84259fe34455af1fd86d374f42c92e0962108c0f65f"
      },
      {
        "src": "/images/optimized/elevator-system-overview-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 94932,
        "sha256": "e9e2a66333857391b5a9d23ded3507c04ad92aeb041f5da82021c8af0a951f2b"
      },
      {
        "src": "/images/optimized/elevator-system-overview-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 176650,
        "sha256": "8f69e3c4116f2db05addbf3c13ed983eb154ccea91285b1de1c2aba8fee845cf"
      },
      {
        "src": "/images/optimized/elevator-system-overview-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 232428,
        "sha256": "6e8da586cc94211ce9800ad5efdf54a3190b7aafd32d012629c398c58f0b377f"
      }
    ]
  },
  "/images/meeting-room-scheduler-blueprint.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2353233,
    "sha256": "ce0f4a6b2771dd93037086317923a7874d751e6d9c2afbeb3cd8b6bd6a86fa94",
    "candidates": [
      {
        "src": "/images/optimized/meeting-room-scheduler-blueprint-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 15406,
        "sha256": "94b4be6ce1d269ad2ec36f88209879e6a1908b7c21a0b50e1548071b0df65710"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-blueprint-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 34894,
        "sha256": "aa210c7f47d6a514f67b6b015025539248a95c8a25d47f19db3c7229ab062ae8"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-blueprint-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 47416,
        "sha256": "b9c4e1bb60a23bd873ae7fd6bdff2f863454c2fbd4432dee328dd0aaaab9b1f2"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-blueprint-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 73128,
        "sha256": "1750cfb2c25faefd432f1e8e5c6f697364da6581f828312d81ed55948b98061a"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-blueprint-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 112840,
        "sha256": "d94e42f333c698f060212b7a1a3069fc44458f431156214eb7984303c1cb4c70"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-blueprint-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 137556,
        "sha256": "e861111a3698b85c1298276dcf642e61118bba2c2181ad9f5f1fc8362dd5dced"
      }
    ]
  },
  "/images/meeting-room-scheduler-entity-flow.png": {
    "width": 1774,
    "height": 887,
    "bytes": 1789772,
    "sha256": "e01a9bb7c1bb166c49bb1a80502e6c045fe252c3d27ee39c3954200769a7c9df",
    "candidates": [
      {
        "src": "/images/optimized/meeting-room-scheduler-entity-flow-384.webp",
        "width": 384,
        "height": 192,
        "bytes": 10124,
        "sha256": "eb8a2af6d3edd180a34ac5814a471cb5489b374ea802df55156601e801ea00ed"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-entity-flow-640.webp",
        "width": 640,
        "height": 320,
        "bytes": 21586,
        "sha256": "c6e513e431f3a2325b51ea3e3991e3146f78416b49eaaa57e7e7986565ad0e17"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-entity-flow-768.webp",
        "width": 768,
        "height": 384,
        "bytes": 28534,
        "sha256": "9832996de110aaee077f677a0d0e8cd6bdf34a1e9c315d573b844f1812760404"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-entity-flow-1024.webp",
        "width": 1024,
        "height": 512,
        "bytes": 44334,
        "sha256": "913106058bd925831a9a17956d864921ad353d9b6d3f70b31e3860bbe40ded3f"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-entity-flow-1360.webp",
        "width": 1360,
        "height": 680,
        "bytes": 68650,
        "sha256": "6df3dd36327ffd01f44df0da95f8965cc9bf3205d3fdb186bdf12a7ed721ffd0"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-entity-flow-1774.webp",
        "width": 1774,
        "height": 887,
        "bytes": 101190,
        "sha256": "fedb5c56cea2b721bb89757689a11f09c207cdcd0ebab3cc66e92416dd336aae"
      }
    ]
  },
  "/images/meeting-room-scheduler-overview.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2683874,
    "sha256": "39bb3c8ebbc7c8ce8b5d6e13db90a86b1bdd3b408396179461578986ecae6a37",
    "candidates": [
      {
        "src": "/images/optimized/meeting-room-scheduler-overview-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 19648,
        "sha256": "a4c1d0fdc49abe25f33862d969298e13ec2cce6a50517243521f3c7ac64898b1"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-overview-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 50382,
        "sha256": "d6b706ce8b86aea3f49285558b152939e100b9c6d48912ad656733754399beb0"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-overview-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 71028,
        "sha256": "9e13222c62bea3ea9b74e64aa39db808ec69dec766b5340b58f9d1bfab2ac8de"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-overview-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 122174,
        "sha256": "d4f06cbd3b238c754417bb143d39ecae0a92a35c764b0772c9ca33617eaea56a"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-overview-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 201202,
        "sha256": "9f6a0ba6128e193acfe01bf7b55ab7d0f3edbff9b7f2f7b3d4b890e78c34985a"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-overview-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 249688,
        "sha256": "d938289831c2b45362c4e0861ab56deab0e8085a41e7eb8b7601ad6f1dc77b6a"
      }
    ]
  },
  "/images/meeting-room-scheduler-room-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 1985223,
    "sha256": "f6828baef138301632a92c505f8afe83b6355b2d90d5b0f220d0b6f5e2bfd12e",
    "candidates": [
      {
        "src": "/images/optimized/meeting-room-scheduler-room-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 10972,
        "sha256": "3ad83a4903abb101d9b8e867ee6696a10481d05d9fd96be4a98d3d38519f2c03"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-room-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 24028,
        "sha256": "95aeeacbd7dfbcfc051c2de8e47ed96701188cca8f32955b7cd3be94bc2edf57"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-room-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 31762,
        "sha256": "2652044fce5dfcff5a702964452d41ff16d0702d29f6755ac471342db0aa3cc0"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-room-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 48776,
        "sha256": "d4ed9eb61dae5c931de7a527d1a2abf15749414c20e19f6945db0be5be699280"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-room-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 73650,
        "sha256": "eef912a75e00a7f3ce2af7ce043d5ffd36d126cb1a069e7bf011316356cf5dca"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-room-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 88080,
        "sha256": "6fd0ce49e9a6e5165a7ecedf15692bab07fca8dbc9ce9f8f2258bebe502332d6"
      }
    ]
  },
  "/images/meeting-room-scheduler-service-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2275310,
    "sha256": "e50c99b6562dacf97b9105a3649924dfbdcd5ff16670a57abf12274bf2587eeb",
    "candidates": [
      {
        "src": "/images/optimized/meeting-room-scheduler-service-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 20958,
        "sha256": "7df0cf060097b269abaa58f55ba3fc0d24baab792c3871bf28d1229318aa5e54"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-service-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 48810,
        "sha256": "23cef2d520e4eaa897101236eb300a8962897bda8f87ee8d92006ea6626aa97f"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-service-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 65560,
        "sha256": "23e80308763df1b445086399d7043966107409c3db7efcaab44a75efc034e59f"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-service-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 99742,
        "sha256": "b4a60358e4b8754d85926139aebcafcc1ba0ed0c7e62f7548bd071a28e235c74"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-service-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 148728,
        "sha256": "12c50e093e2a02d1d3c5bb2d7bcf46083aefe3112cf9f853e7396ef3c6f81b06"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-service-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 178270,
        "sha256": "38f20663c187a34d0fa4e553eb2e19c1ef8ae29389a07871325676feeac7eb81"
      }
    ]
  },
  "/images/meeting-room-scheduler-strategy-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2191840,
    "sha256": "e6a1812b9be24887046606c2f2cd2248d938b826b21815d07bfeb6489a8217d3",
    "candidates": [
      {
        "src": "/images/optimized/meeting-room-scheduler-strategy-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 12146,
        "sha256": "a01a9713e89c9c1ea2896599d0c3509d464361d808c18c9186ceb8dbf1a161ed"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-strategy-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 28834,
        "sha256": "fabe57d0ba1a74cfe418869d3a093c492bfc4768e570f160eb5ee0d768dcf75e"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-strategy-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 37442,
        "sha256": "23b9a62a20a2253abe8e31e8364bd7060df1466909c8ad081607656e66a22556"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-strategy-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 58946,
        "sha256": "36a95850e069b04b0193dd864fff347850f56d380ca51c7b6d0805c33de42beb"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-strategy-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 88976,
        "sha256": "097e37bb9b7c71f4cde97676c48d756e296226b1c94ea4c45f238bd72016f091"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-strategy-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 107706,
        "sha256": "a13dc234fc35901ecbea7378a3db776d9ff73072e53979583aed41d345da5ffd"
      }
    ]
  },
  "/images/meeting-room-scheduler-values-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2696075,
    "sha256": "7303c091c9957dd2ef4761e60437d2c832c436cf263d2554803553ebbc2466a5",
    "candidates": [
      {
        "src": "/images/optimized/meeting-room-scheduler-values-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 17770,
        "sha256": "232f5c563b194b9cb29d06ff7a1262725eb2f130029038f8deb99acf3f927808"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-values-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 45178,
        "sha256": "9d0d9c0e99a12a773e3fc781e06e6ff93251b05c175d37c22c559c336f5cfc8c"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-values-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 59730,
        "sha256": "301ad0e6a118e52c3d1c686c438c3d8aea022b253c3e8402252174065a257bec"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-values-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 100804,
        "sha256": "0f860f831085eca39ad5634020a6b1fa3515c4cb1af0b4b7d2e0621d88d19c2d"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-values-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 166488,
        "sha256": "b98d38684145fc9bd84891fe8fc02c1962410430de1dfb789124c30b0bb1e23b"
      },
      {
        "src": "/images/optimized/meeting-room-scheduler-values-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 204750,
        "sha256": "1874923b70ddbed231e17507361514572138bdb16504736710112b14466a4b2b"
      }
    ]
  },
  "/images/movie-ticket-booking-entity-flow.png": {
    "width": 1774,
    "height": 887,
    "bytes": 2257993,
    "sha256": "92390f8667ac7e7aa46cb1a7f447c018245da9a1be0b7e806cdd6d85507790c2",
    "candidates": [
      {
        "src": "/images/optimized/movie-ticket-booking-entity-flow-384.webp",
        "width": 384,
        "height": 192,
        "bytes": 12046,
        "sha256": "ad1798cf7448beb6218fe07ac6e2649ed9db00454cd90f90132b35254de1f033"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-entity-flow-640.webp",
        "width": 640,
        "height": 320,
        "bytes": 25834,
        "sha256": "ef8a8a8fd714cc8148a09cad127fa418a2839f555398e830de1cefdf007eb7db"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-entity-flow-768.webp",
        "width": 768,
        "height": 384,
        "bytes": 34774,
        "sha256": "32d61b92060a8ffd283dbf23bd3db7ddc1036a3fa5e45186e0e85c12853a1f0d"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-entity-flow-1024.webp",
        "width": 1024,
        "height": 512,
        "bytes": 57274,
        "sha256": "8a511800bf4b1b55265ab0709de0e893863010f14034f7d514645b49a4f330a3"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-entity-flow-1360.webp",
        "width": 1360,
        "height": 680,
        "bytes": 93046,
        "sha256": "73dc5220a55fac8098612118430a1c71739ea19631f1daf00c04593710eba185"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-entity-flow-1774.webp",
        "width": 1774,
        "height": 887,
        "bytes": 148484,
        "sha256": "f5cf9de067f6b8b3d8d189637c67d8a8eeb8e2c989a8e83a3cc39a27e1fb5185"
      }
    ]
  },
  "/images/movie-ticket-booking-overview.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 3152452,
    "sha256": "2fbf839495cf1084fdbd1869320f676b9fd860652fbf5d4c5100213718f885fa",
    "candidates": [
      {
        "src": "/images/optimized/movie-ticket-booking-overview-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 21106,
        "sha256": "c418a42e20d71a4c1bf5c33dcc4316df995a4e0cf934dff763378a184a019fbb"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-overview-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 58630,
        "sha256": "ca00fa974eace50c96cccb1ce062fb09afb6dfc2ab8c6068f5cb8c8aae5f9ad6"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-overview-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 82846,
        "sha256": "8965e273e0b55bf4b11387561e6a663aef821f33a524a11d5a433231c11e4fce"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-overview-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 143026,
        "sha256": "b6a25d64e3f4724d5ba73511facf139daeddb9d46c20f501f535cf1957436bc3"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-overview-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 243170,
        "sha256": "6ebca766cccca1d64451b54f938e42c33b04ae4778d51856e11abece20361c70"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-overview-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 304326,
        "sha256": "1a4497a15bd55520f2ec363205b319205cd08b2438fe91659396ee2c5523c8f7"
      }
    ]
  },
  "/images/movie-ticket-booking-physical-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2138178,
    "sha256": "88e4bebcc6837284735cc490996487a5371cd37ece4eb358cd47630ebb7725a8",
    "candidates": [
      {
        "src": "/images/optimized/movie-ticket-booking-physical-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 6084,
        "sha256": "f6959dafbf19f988d989fb4944815e1d064b57f9d2a9eaaa2b4b54b2d03096ce"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-physical-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 13530,
        "sha256": "ac6d2fbe7fe9a1461c90ce478fe2f95c34a0284c58b19d2a934f3a0edeabede2"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-physical-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 17896,
        "sha256": "19b8178b8482bc7630f6fbf594ff89dcb7257fcef9bc7af8d6d261441412fc42"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-physical-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 29780,
        "sha256": "714e9f211dc8198883b57c9292afb97ca9f6c9172c2a7578f627cdbd2d59b805"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-physical-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 50720,
        "sha256": "c67bd9beda0bd79414a754b4b46a615443ab5af783e4b224931c65f17b8302e6"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-physical-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 65266,
        "sha256": "ef445868434787f630832fdff5b79036bb124c7e50357d79485168269f30b52e"
      }
    ]
  },
  "/images/movie-ticket-booking-service-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 1869210,
    "sha256": "fc9d04026b12a9fd809c448af5eadab294f8db72fa8795d7767cfa81563bb9b9",
    "candidates": [
      {
        "src": "/images/optimized/movie-ticket-booking-service-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 15336,
        "sha256": "048da9d0beb8c9423530c8b08e65698eefdaa97336f9a5963eaf5f96ef938ea9"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-service-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 35078,
        "sha256": "36a74f647566437b8c75f1cc3627a11339a9659d055a1d7166a4785f8d395452"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-service-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 47754,
        "sha256": "ba233104c118a4b3c28b0796779cf547b27f45f7519db081db25c1ce6fead5d6"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-service-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 75452,
        "sha256": "61d27660b421fab3dbac12a1f44b78e5c9d7aaa3f89e17f0eb6c6664ba3e8c7e"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-service-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 111540,
        "sha256": "e6b205340b35cd646eb31f4caf749cc2dd9eb62a22f06f61a4df2be6e7e0669b"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-service-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 132050,
        "sha256": "fa8c343933464b7c52a18d770258e3574e0acc1110e1b52fad2d09cdc0fc183e"
      }
    ]
  },
  "/images/movie-ticket-booking-show-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2329690,
    "sha256": "8d27abc63a6720484f6446d373460f8dc461f147d637a76b522010f9ac5d494e",
    "candidates": [
      {
        "src": "/images/optimized/movie-ticket-booking-show-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 11728,
        "sha256": "a29f5819f45e180640e48273b9772ed5edd2ebbc6fee2502547366a4f28b3887"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-show-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 27948,
        "sha256": "a312640b3209bcf03e0878e3e6455ba5fcf6a9091829492af00acc84f9f5dff0"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-show-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 36336,
        "sha256": "8a082a9240d07a201c8302d4f6ba823f9e44c85f4d2625a4c41aa7545101317d"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-show-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 56260,
        "sha256": "d884ebe0457b10169e353ae97cd60b03b99ffad6e5d04e270a617d98d788af7d"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-show-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 88804,
        "sha256": "31b2249a3112478abaa502c0da4aa7fa3e71cf133e53a2dedb0028e7e477dabf"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-show-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 108368,
        "sha256": "7f4b1e095230bf8abf27fba6005204ab02915cf6e729e738d9c12f4f3388580a"
      }
    ]
  },
  "/images/movie-ticket-booking-show-seat-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2093075,
    "sha256": "6d21788dad65c41121e51d680c9c537fe937013da1842b8472e739a13cc4e76c",
    "candidates": [
      {
        "src": "/images/optimized/movie-ticket-booking-show-seat-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 13300,
        "sha256": "b7e3d78af6a65aff873607ae0fa1db031816c3c9358aa6a8a631fa7a6201083c"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-show-seat-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 30600,
        "sha256": "be4749b86dd789ce095dc62d55f6be1c1eda0dd4a15ec4e8b87ad5b2bb4e2d21"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-show-seat-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 38968,
        "sha256": "5fe2def7adbc3758fcbc4e1e6d9e1713a83fe192f44a67f50fb8c65a299e98c1"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-show-seat-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 59648,
        "sha256": "37d8c9a9d996627b1fafb9c4b831b63c844baec2a1385733a7ab94e33039c652"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-show-seat-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 89406,
        "sha256": "4146da54bf2ef7ba6680a5adfab886d544c24e2e0ba849b5ad7eea4b7f84b137"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-show-seat-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 106910,
        "sha256": "5a2d70d052fd974845e5cdd81d06322509b0101d4aa4de391b9ed992a5767e8a"
      }
    ]
  },
  "/images/movie-ticket-booking-values-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2282714,
    "sha256": "6dd521377245e01995871c0e4857acc71e15b72df0a95e3904df6aadbbbd16a2",
    "candidates": [
      {
        "src": "/images/optimized/movie-ticket-booking-values-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 17864,
        "sha256": "242b4511c918325beda08fe61e6d01f59b9e70d37cc01856318847b7e9a9af5a"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-values-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 41402,
        "sha256": "40d15a72be19ee5bf5bea43a8d76216908bb84b4a7cde9c74dd6eadcc5aa2b89"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-values-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 53910,
        "sha256": "861c7d5679b5fe0546cc0f4c44c7c48fecd49ba40f40e111676c6c69cbed356f"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-values-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 85154,
        "sha256": "fe26086798b77156a02e1872a2a32b89c6130babeca8fbbf8c7eeec3f850a9d7"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-values-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 126648,
        "sha256": "4819ec85609f6da80cb9c4f4dfaf5d21ea1a057a9018815d8823a89459471052"
      },
      {
        "src": "/images/optimized/movie-ticket-booking-values-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 153970,
        "sha256": "2faa71a252c4dfe5acbc207168cc6a40aadab5caca8a03688e0edc681163d301"
      }
    ]
  },
  "/images/notification-system-blueprint.png": {
    "width": 1692,
    "height": 929,
    "bytes": 1955259,
    "sha256": "6fe77ef96e59f2ee8e61e0e3a88facbe598a37a323ad7c331b84fb7866dbefe0",
    "candidates": [
      {
        "src": "/images/optimized/notification-system-blueprint-384.webp",
        "width": 384,
        "height": 211,
        "bytes": 13714,
        "sha256": "961827fea4cb4adc4b75d7855fd6eade42271e7bd510e32a3bead3587fa4bc61"
      },
      {
        "src": "/images/optimized/notification-system-blueprint-640.webp",
        "width": 640,
        "height": 351,
        "bytes": 32470,
        "sha256": "2039976ca75109aebdcc9fa305c7aa6a33e9ade2cbf3fcac1450184b78377fb8"
      },
      {
        "src": "/images/optimized/notification-system-blueprint-768.webp",
        "width": 768,
        "height": 422,
        "bytes": 41786,
        "sha256": "ceca9b924239828b2ab335332465bdee411459b118a19750c443d16812a7af5e"
      },
      {
        "src": "/images/optimized/notification-system-blueprint-1024.webp",
        "width": 1024,
        "height": 562,
        "bytes": 65072,
        "sha256": "f5ef357f08dbdff71a0226d85984bc751fa1259e3e677d18fa1c5f7e1bfd3ba5"
      },
      {
        "src": "/images/optimized/notification-system-blueprint-1360.webp",
        "width": 1360,
        "height": 747,
        "bytes": 100240,
        "sha256": "56951abd34f10a359f4f739e3fd960ca3939770578bccbc7c400d878f7f899a6"
      },
      {
        "src": "/images/optimized/notification-system-blueprint-1692.webp",
        "width": 1692,
        "height": 929,
        "bytes": 131918,
        "sha256": "9e4a2b9bef3b2bbe8f7b563af31d67eda1b96e1ea723e552115115c12f5c9379"
      }
    ]
  },
  "/images/notification-system-entity-flow.png": {
    "width": 1692,
    "height": 929,
    "bytes": 1999900,
    "sha256": "bbfc2ce6c1e3d319a8e70863c25b85d8c5c0affdcab95b8a998b67c16bfe5b17",
    "candidates": [
      {
        "src": "/images/optimized/notification-system-entity-flow-384.webp",
        "width": 384,
        "height": 211,
        "bytes": 10130,
        "sha256": "d42252800ee2b1164589bb8faeecb230ef0635106e7a4a4d09a58f53e64c8594"
      },
      {
        "src": "/images/optimized/notification-system-entity-flow-640.webp",
        "width": 640,
        "height": 351,
        "bytes": 23130,
        "sha256": "62a748929ade63f33f04d04711bda44ce6a7e8098297da147b0cc6ae2252245e"
      },
      {
        "src": "/images/optimized/notification-system-entity-flow-768.webp",
        "width": 768,
        "height": 422,
        "bytes": 30570,
        "sha256": "32ea4f78a1e34f0a0dccd685f4563d7221dd04b021595a8844bf6e98f03af69e"
      },
      {
        "src": "/images/optimized/notification-system-entity-flow-1024.webp",
        "width": 1024,
        "height": 562,
        "bytes": 49564,
        "sha256": "3e12968efaa0d42c50a4f0e28289c9a607fe798e677646a946009865a5a0a080"
      },
      {
        "src": "/images/optimized/notification-system-entity-flow-1360.webp",
        "width": 1360,
        "height": 747,
        "bytes": 80792,
        "sha256": "a6378ec67d525bfd482604b5fa2284cd0351ea6242d94b4299d424469c1a1bb3"
      },
      {
        "src": "/images/optimized/notification-system-entity-flow-1692.webp",
        "width": 1692,
        "height": 929,
        "bytes": 113058,
        "sha256": "39ea63736dc9f14754228ab7443b666ddcb5ffbefd0c3745aa873dcf48b34765"
      }
    ]
  },
  "/images/notification-system-job-class.png": {
    "width": 1693,
    "height": 929,
    "bytes": 1943192,
    "sha256": "74dbbdf16f1c367311b039d068063e598a4f8793b21c294ec4def6f00a0adcb1",
    "candidates": [
      {
        "src": "/images/optimized/notification-system-job-class-384.webp",
        "width": 384,
        "height": 211,
        "bytes": 7336,
        "sha256": "5c2b2eb1019baf477ad59157c9ffb5128ef1417cb160b912082348be533f018b"
      },
      {
        "src": "/images/optimized/notification-system-job-class-640.webp",
        "width": 640,
        "height": 351,
        "bytes": 17550,
        "sha256": "9acf9d419f01cb1a8ab0efb2ff833339c1c56f4c59516068b75bd43a567e1349"
      },
      {
        "src": "/images/optimized/notification-system-job-class-768.webp",
        "width": 768,
        "height": 421,
        "bytes": 23826,
        "sha256": "13ef34b3cc4ffdcda86d2bf6de0a139e2d250ea727d3d1424b241499eae78abf"
      },
      {
        "src": "/images/optimized/notification-system-job-class-1024.webp",
        "width": 1024,
        "height": 562,
        "bytes": 37898,
        "sha256": "635bda1b5d0f1f025c208e0b725b57fa444e969a75559ffc7b5cc3a93eb5e0dd"
      },
      {
        "src": "/images/optimized/notification-system-job-class-1360.webp",
        "width": 1360,
        "height": 746,
        "bytes": 62060,
        "sha256": "7c524a66a8ce06f8c37cc595eb9a132fc207c543b9381f740c85b8c60326e498"
      },
      {
        "src": "/images/optimized/notification-system-job-class-1693.webp",
        "width": 1693,
        "height": 929,
        "bytes": 90494,
        "sha256": "867f98d5c5bf99e15fb84625d7be4babfd440f0696f2dd4bbf5e73fcb0bb604c"
      }
    ]
  },
  "/images/notification-system-overview.png": {
    "width": 1693,
    "height": 929,
    "bytes": 2151225,
    "sha256": "7b247a87159d3a1c578f6a45fb8e713643a46f850f1388d254fa0b2d7d243adf",
    "candidates": [
      {
        "src": "/images/optimized/notification-system-overview-384.webp",
        "width": 384,
        "height": 211,
        "bytes": 9012,
        "sha256": "6d9241542bbaaa55270928401f453baab48d39268bb9fd468fd1ab5f8e9c3635"
      },
      {
        "src": "/images/optimized/notification-system-overview-640.webp",
        "width": 640,
        "height": 351,
        "bytes": 18332,
        "sha256": "0066d1960fa8e1fc4142038fa81dd6a6f215b583d782c9068ddbb06737c125fb"
      },
      {
        "src": "/images/optimized/notification-system-overview-768.webp",
        "width": 768,
        "height": 421,
        "bytes": 24588,
        "sha256": "d745a4d90ce501010c7b2b7b8b72904f09149cb5a324983f189ee5de9d6a65d3"
      },
      {
        "src": "/images/optimized/notification-system-overview-1024.webp",
        "width": 1024,
        "height": 562,
        "bytes": 40088,
        "sha256": "f05fbcf580d44ce19f24c76e0c57bedde57df4e57a6d825bf611246249234337"
      },
      {
        "src": "/images/optimized/notification-system-overview-1360.webp",
        "width": 1360,
        "height": 746,
        "bytes": 65374,
        "sha256": "4d5006c1ec420d54f4d048f8b31a6552b7bc3cf59d119b0db82acef5c6dd26af"
      },
      {
        "src": "/images/optimized/notification-system-overview-1693.webp",
        "width": 1693,
        "height": 929,
        "bytes": 100196,
        "sha256": "225da9211d45d322e5281ede2a128c18831fd075b8883b98ae07382786dfff8c"
      }
    ]
  },
  "/images/notification-system-senders-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2323148,
    "sha256": "bdf6a896c734835cfba0d7876fc16fb7ce799e09e94771cac43409ff170f52f2",
    "candidates": [
      {
        "src": "/images/optimized/notification-system-senders-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 13300,
        "sha256": "97b2cbc145592088da9c16ae6027c1badc49678bc31aed31e1d16597e962cf70"
      },
      {
        "src": "/images/optimized/notification-system-senders-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 30368,
        "sha256": "3b6566a7eef5eeb8a48ae10ac906b3abbefb043380d92f220f4cd4b6ede550db"
      },
      {
        "src": "/images/optimized/notification-system-senders-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 39162,
        "sha256": "3c0e26195c1aa08c4e863933e07d98c1388588d9597f2019cdd3519381c04bec"
      },
      {
        "src": "/images/optimized/notification-system-senders-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 60534,
        "sha256": "4d31101ef4785ae3451794c446baf956fadb776880e64b6f85b798d5aa62ad7c"
      },
      {
        "src": "/images/optimized/notification-system-senders-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 94586,
        "sha256": "e70d1aff8cc88828c61806bb90a055c303b96650b269b526450cde30ad1c2429"
      },
      {
        "src": "/images/optimized/notification-system-senders-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 117018,
        "sha256": "feeb6d7f7a08e089db9c915850aa58927326c023aeeccfb3b64ee25c22db797e"
      }
    ]
  },
  "/images/notification-system-service-class.png": {
    "width": 1693,
    "height": 929,
    "bytes": 1988524,
    "sha256": "d78b388c6b760323edd8d9859651194c92ce80ea0ccd65581231ef319b7b55e5",
    "candidates": [
      {
        "src": "/images/optimized/notification-system-service-class-384.webp",
        "width": 384,
        "height": 211,
        "bytes": 11570,
        "sha256": "3727af76f3426cbfb55fb2f6c56022df9d1935d04463f72b915b084a93913369"
      },
      {
        "src": "/images/optimized/notification-system-service-class-640.webp",
        "width": 640,
        "height": 351,
        "bytes": 28380,
        "sha256": "dbcbbc649b4daf78df70991dea2251b76dd42893b3a9e352037d28472a65f701"
      },
      {
        "src": "/images/optimized/notification-system-service-class-768.webp",
        "width": 768,
        "height": 421,
        "bytes": 37798,
        "sha256": "c5e3c4f1b38604b9ac177f927e1c2636dcbe85495c4f20fc1e971c89872364f1"
      },
      {
        "src": "/images/optimized/notification-system-service-class-1024.webp",
        "width": 1024,
        "height": 562,
        "bytes": 57874,
        "sha256": "7c42092b3a3e49eb60cfbf138a4ee71a9dea545cc72574a8ad461a0ce6173159"
      },
      {
        "src": "/images/optimized/notification-system-service-class-1360.webp",
        "width": 1360,
        "height": 746,
        "bytes": 89426,
        "sha256": "76710fe8c203a231f2a2cea026414da74415b6679e01702895665653249e07d2"
      },
      {
        "src": "/images/optimized/notification-system-service-class-1693.webp",
        "width": 1693,
        "height": 929,
        "bytes": 124892,
        "sha256": "78dccd6b5acce07f51ce79056213185e258b98aa7a85b7433bb9a9638a278f51"
      }
    ]
  },
  "/images/notification-system-values-class.png": {
    "width": 1693,
    "height": 929,
    "bytes": 2003983,
    "sha256": "2a061ea9e2d8b65c34dcb3ea21afb3cf530fd1a8d5d1a012cc08ca3c89306fb7",
    "candidates": [
      {
        "src": "/images/optimized/notification-system-values-class-384.webp",
        "width": 384,
        "height": 211,
        "bytes": 11724,
        "sha256": "4e537f1b805da5d3d6ee66218e981ed5623b5b9be717fbe01409d5efbfd06701"
      },
      {
        "src": "/images/optimized/notification-system-values-class-640.webp",
        "width": 640,
        "height": 351,
        "bytes": 25536,
        "sha256": "c6624bdb69a4d3474ecc23573de84ff56be00d209b568bbd67439269c9b69aa5"
      },
      {
        "src": "/images/optimized/notification-system-values-class-768.webp",
        "width": 768,
        "height": 421,
        "bytes": 34302,
        "sha256": "6dc53324ed8487fe5babebd336d9fc2d9cfe63f4cce2801e159dde478e6c590b"
      },
      {
        "src": "/images/optimized/notification-system-values-class-1024.webp",
        "width": 1024,
        "height": 562,
        "bytes": 51498,
        "sha256": "3b84ec11a81bdcdd9b5c702cb4593963db5ca23712922f20abfd59b5b59408e1"
      },
      {
        "src": "/images/optimized/notification-system-values-class-1360.webp",
        "width": 1360,
        "height": 746,
        "bytes": 79660,
        "sha256": "1acdc8ea68197b86446e091b7c8ba9d00ff7690b11fec43988487c74f561d459"
      },
      {
        "src": "/images/optimized/notification-system-values-class-1693.webp",
        "width": 1693,
        "height": 929,
        "bytes": 109964,
        "sha256": "06cd60128ab69403945fb018dc9374636c3ba02f034f7463a5e1395894905096"
      }
    ]
  },
  "/images/parking-lot-entity-flow.png": {
    "width": 1774,
    "height": 887,
    "bytes": 2074979,
    "sha256": "e9c6694169cf857fda0697128b077ffc3a09b546bd856dac7684767c32dab69e",
    "candidates": [
      {
        "src": "/images/optimized/parking-lot-entity-flow-384.webp",
        "width": 384,
        "height": 192,
        "bytes": 9612,
        "sha256": "d14fb664180f20dd9795bbffc41116ebed25c7d200aadd549d2879b5a5aa8bec"
      },
      {
        "src": "/images/optimized/parking-lot-entity-flow-640.webp",
        "width": 640,
        "height": 320,
        "bytes": 21254,
        "sha256": "522de3235681b538f6a3a17d30aa4f98dcc01151858833b6ac5c6b6b1dd82213"
      },
      {
        "src": "/images/optimized/parking-lot-entity-flow-768.webp",
        "width": 768,
        "height": 384,
        "bytes": 27774,
        "sha256": "90eb77af9fda6ae49c024450ae5cf3e8620612873c58bc8c43f4d053b9b9150f"
      },
      {
        "src": "/images/optimized/parking-lot-entity-flow-1024.webp",
        "width": 1024,
        "height": 512,
        "bytes": 43090,
        "sha256": "eec30a826d5964517f97f07c7cda01eb96b34652a79d3d5858f6d17d859d871f"
      },
      {
        "src": "/images/optimized/parking-lot-entity-flow-1360.webp",
        "width": 1360,
        "height": 680,
        "bytes": 71314,
        "sha256": "bc8d2e5af22a583e87952bc4b1a4735f15513ff328ec41e93aad4a19c7219fbd"
      },
      {
        "src": "/images/optimized/parking-lot-entity-flow-1774.webp",
        "width": 1774,
        "height": 887,
        "bytes": 114770,
        "sha256": "17eac72938ee32f173d8e2d209c8b80a84682adc79604396b9129675dd9bc9e5"
      }
    ]
  },
  "/images/parking-lot-floor-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 1987305,
    "sha256": "278c44fa5d381d153ca502224837a459122c203afccf148f2032f5ab94673c79",
    "candidates": [
      {
        "src": "/images/optimized/parking-lot-floor-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 8866,
        "sha256": "bb252d5a6298d082f8d5429d191c5c3b4ca9b93fb05df75a8be4d0e783b1f42e"
      },
      {
        "src": "/images/optimized/parking-lot-floor-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 18838,
        "sha256": "a7452c1da8a046eb08100a4e15fe6f64ce71cb0be4567ad849976e1d440e173a"
      },
      {
        "src": "/images/optimized/parking-lot-floor-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 23466,
        "sha256": "03f6c9fbb180badd6634f0efe4f0a384d36f9e096bb04d1fa7a13f5b384e78f0"
      },
      {
        "src": "/images/optimized/parking-lot-floor-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 35780,
        "sha256": "e17ec29171cdbf19b6c636b682311bebab9494e15c0cf45caf9c418c38b45dff"
      },
      {
        "src": "/images/optimized/parking-lot-floor-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 54112,
        "sha256": "a74108cb375f71674a8ca7a2c47ac9aab6f347b57fb5c86012eae9fc359502d7"
      },
      {
        "src": "/images/optimized/parking-lot-floor-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 64286,
        "sha256": "909f9ace99851f6b86199a4698a41f16a52d46e5ff37a68249e1b58a152c116c"
      }
    ]
  },
  "/images/parking-lot-overview.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 3040469,
    "sha256": "6b79b1d8d43d3d22d5975a4dafd64ea97d690b062d581161c41643c7b7d85773",
    "candidates": [
      {
        "src": "/images/optimized/parking-lot-overview-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 14098,
        "sha256": "444ffdf558c9b75cf0106410a991e07f18959c1f4b56cf6d21de98bcd7d15684"
      },
      {
        "src": "/images/optimized/parking-lot-overview-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 42046,
        "sha256": "718defd09f5aeb800163a7df3001c7a71b98d6e7275bf08fe576f3144f147d97"
      },
      {
        "src": "/images/optimized/parking-lot-overview-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 63672,
        "sha256": "c916df08a345dab48c12c0a26e3285276e05207d5d212911ed12f89553caa53a"
      },
      {
        "src": "/images/optimized/parking-lot-overview-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 123902,
        "sha256": "41928fbaaf895557dd6c8cd14c4f2dd3d8f06c3afb9778c8e3c361173e91bee8"
      },
      {
        "src": "/images/optimized/parking-lot-overview-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 221748,
        "sha256": "6e2de149b302547cec31f1498dc582af7e9e7479866cf13940be7c21b8ad984b"
      },
      {
        "src": "/images/optimized/parking-lot-overview-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 279382,
        "sha256": "4a231a45f45559358bcf94011a3caff81a992360e331a93c45d2e37996a27874"
      }
    ]
  },
  "/images/parking-lot-spot-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2066030,
    "sha256": "0153fde26d9bcff1eb8a5e1760abf464fa9b87d9359cdd8ad89b698ad54aabe9",
    "candidates": [
      {
        "src": "/images/optimized/parking-lot-spot-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 11478,
        "sha256": "4646354cd866a720f6465a1ecdf8208f58a7e2b69bfff70454a0de4d1a1f7d23"
      },
      {
        "src": "/images/optimized/parking-lot-spot-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 24068,
        "sha256": "57c29d3687ca1b57bc06a4c144682453a4e7dc24334504a475b29131a9f6baec"
      },
      {
        "src": "/images/optimized/parking-lot-spot-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 30888,
        "sha256": "874ca2364efe15775be0a0f8bd4146c6f68003edb2de1bf3743e16aa5145ce67"
      },
      {
        "src": "/images/optimized/parking-lot-spot-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 47308,
        "sha256": "4f821fa7b34c3b63bc4137a16e4f3206cb1878a8c0ffa66364264c7d9a1c9654"
      },
      {
        "src": "/images/optimized/parking-lot-spot-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 72822,
        "sha256": "6eb53eb5653487e2b2e64318efe7c57b9c33ba8669b8299a3f82cc14dfb88ddb"
      },
      {
        "src": "/images/optimized/parking-lot-spot-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 85648,
        "sha256": "3377f0da04c3365336df999af6ec83f8042fde9e41875e467fd6fb37955a34ea"
      }
    ]
  },
  "/images/parking-lot-strategy-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2005686,
    "sha256": "52227fbb5bfa7fe975609fc6283ffa5db9f2dad4ccdc80b40942294717f97ccd",
    "candidates": [
      {
        "src": "/images/optimized/parking-lot-strategy-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 10018,
        "sha256": "f033c946c7a2528cee5b0072e0bb8eeeee5616846cc57697f42434d5beba984a"
      },
      {
        "src": "/images/optimized/parking-lot-strategy-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 22732,
        "sha256": "5187a2d3d257b30f6a4e1965cf474fb6203fa47ab2b23cb4f1af95a238041603"
      },
      {
        "src": "/images/optimized/parking-lot-strategy-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 29038,
        "sha256": "a50616cbeef9b5e5ac73e231771193558a60fa157ebef8599cb21ecd25e738a7"
      },
      {
        "src": "/images/optimized/parking-lot-strategy-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 44078,
        "sha256": "4d8ab059a3971674511bc646fa93d1515e2df4df3daff5ae5172bcd8e4d40b0f"
      },
      {
        "src": "/images/optimized/parking-lot-strategy-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 66442,
        "sha256": "19498b04f7ce6225a74ebe1d65b073400b3c6343105b009200d7f7cf103a5c71"
      },
      {
        "src": "/images/optimized/parking-lot-strategy-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 77990,
        "sha256": "ff298034fbafb7ea295d4ab3813c6645a657efe4ea5c3d5c65a7ea2057c3ed7c"
      }
    ]
  },
  "/images/parking-lot-system-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 1876711,
    "sha256": "4b038208e8a8c1e24464a191b8b3c045239b1c1718b8bfa9aa51a8822686be9c",
    "candidates": [
      {
        "src": "/images/optimized/parking-lot-system-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 10770,
        "sha256": "5a06c9267375d9213c937b5468894107b28ab4a5b7a34319bb0fa526c156092e"
      },
      {
        "src": "/images/optimized/parking-lot-system-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 24476,
        "sha256": "1194a8610b0df40f305ac577f0e1b8b7eae6beb28f5cf811221b22e899054c73"
      },
      {
        "src": "/images/optimized/parking-lot-system-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 31212,
        "sha256": "b67ff38796c95e66a39d75969aa7e7b98560f650003bd1b5b37ae660b7ce2fb9"
      },
      {
        "src": "/images/optimized/parking-lot-system-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 46444,
        "sha256": "0ecab4d10c42c7e010c910507e2d78b40bda7084c4f39f12133fc72dbe7decad"
      },
      {
        "src": "/images/optimized/parking-lot-system-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 69730,
        "sha256": "b39154f6d6e327f461997520407ca8efdebc80511a55bab85d462951e4cb3911"
      },
      {
        "src": "/images/optimized/parking-lot-system-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 81326,
        "sha256": "639bcd265f870289093e8cbf9f3b1b39fd4ea5784a529d3f70a2960590f99f6c"
      }
    ]
  },
  "/images/parking-lot-values-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 1710414,
    "sha256": "204032c1ad5094df28243d8abd2ec462c1418097492330c617028d7193d9aad6",
    "candidates": [
      {
        "src": "/images/optimized/parking-lot-values-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 13126,
        "sha256": "c05f91cb23616de270985aab9e2a058ae4215f2ba7528e866c685a15d9c90a77"
      },
      {
        "src": "/images/optimized/parking-lot-values-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 28100,
        "sha256": "4b914ff44af6666e05ed5ad8cbbcb0196f3fc5b4772eadc47fab68728d48aee5"
      },
      {
        "src": "/images/optimized/parking-lot-values-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 35584,
        "sha256": "89188a7d43b9168a1f93099023cd67cdf851e73056c9bb13a8c5a267144bbc47"
      },
      {
        "src": "/images/optimized/parking-lot-values-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 52076,
        "sha256": "02efedbab3ce63862b413d93d957cf241d5fbc8e609bd4a7ae10dadd12ffae6e"
      },
      {
        "src": "/images/optimized/parking-lot-values-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 75340,
        "sha256": "b83447413b9c9effbbd8b6c51bf659e05de39396083080827bd0ba49ecff9ed6"
      },
      {
        "src": "/images/optimized/parking-lot-values-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 88254,
        "sha256": "0d944565f67ba8da160cf11dc0e7a67b128e287edd8595cf7c853b1e0861b3eb"
      }
    ]
  },
  "/images/ride-sharing-entity-flow.png": {
    "width": 1692,
    "height": 930,
    "bytes": 1043049,
    "sha256": "71089d78a48cbeb217c946f908ce578456483264f7e49110f8ea3b863612e33b",
    "candidates": [
      {
        "src": "/images/optimized/ride-sharing-entity-flow-384.webp",
        "width": 384,
        "height": 211,
        "bytes": 6918,
        "sha256": "28190b9bed22cfa0936ef518589e4f9c610a8eb74b862fb5d584f4976827d87c"
      },
      {
        "src": "/images/optimized/ride-sharing-entity-flow-640.webp",
        "width": 640,
        "height": 352,
        "bytes": 14654,
        "sha256": "b21700aab905208e349064887ef2feb10908ca500a2add0ed6f73b4b2f11ab7e"
      },
      {
        "src": "/images/optimized/ride-sharing-entity-flow-768.webp",
        "width": 768,
        "height": 422,
        "bytes": 18934,
        "sha256": "75200cff4ffbc8e6c084f6ffd2cd900acf18605bbf870e9fd4ea6c488309281a"
      },
      {
        "src": "/images/optimized/ride-sharing-entity-flow-1024.webp",
        "width": 1024,
        "height": 563,
        "bytes": 28322,
        "sha256": "5270b04022b729d845f9be7c346e0aac98929d119a4eacb5968cbab855a12416"
      },
      {
        "src": "/images/optimized/ride-sharing-entity-flow-1360.webp",
        "width": 1360,
        "height": 748,
        "bytes": 41534,
        "sha256": "945501da1307d96570624e7d03ee4adf8e839ac7021f34a726dce8ee8b51f68b"
      },
      {
        "src": "/images/optimized/ride-sharing-entity-flow-1692.webp",
        "width": 1692,
        "height": 930,
        "bytes": 55462,
        "sha256": "c5ec8a107fb7d063e0e2306eba33754f7113a7508c781237ba205fe4b9c52bfc"
      }
    ]
  },
  "/images/ride-sharing-graph-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 1887842,
    "sha256": "dc7a22a5fd0210ad905d3182056beab9589c452cfc177d583660d5e8aac58828",
    "candidates": [
      {
        "src": "/images/optimized/ride-sharing-graph-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 10662,
        "sha256": "ea1a0c8172faf302c99148c4a67424d7cc690c2cb786c572c8a4f570769e74e6"
      },
      {
        "src": "/images/optimized/ride-sharing-graph-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 21200,
        "sha256": "648dd1d25e8ebb88902babf0dfc8fbc05656fdb99e8a23f131ceb537d108ca8f"
      },
      {
        "src": "/images/optimized/ride-sharing-graph-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 27536,
        "sha256": "6361c8607c45bbbd0f878f1b1a3b7f45e47e1464e477eff046577e376ca68a21"
      },
      {
        "src": "/images/optimized/ride-sharing-graph-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 41592,
        "sha256": "4ca354c173a9ee7675b5b0dc2046f325b87e404c592e220f7b57fd3aef52774e"
      },
      {
        "src": "/images/optimized/ride-sharing-graph-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 63142,
        "sha256": "ef188c537913aff68aea1b87c33536eb33f102eabadb169a475ccd7d8466bb6d"
      },
      {
        "src": "/images/optimized/ride-sharing-graph-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 73590,
        "sha256": "b40ae2f62f71a12001d5aeb39a239a23aa38da72d2aa9c99136462012806e494"
      }
    ]
  },
  "/images/ride-sharing-overview.png": {
    "width": 1690,
    "height": 931,
    "bytes": 1672403,
    "sha256": "bada2f13ec218570609b21441334607d724e3248485f28499c49239a7692536a",
    "candidates": [
      {
        "src": "/images/optimized/ride-sharing-overview-384.webp",
        "width": 384,
        "height": 212,
        "bytes": 15532,
        "sha256": "253a2c460be81359064c9b6bac5f3a265072fa7d988ce6445e7d627857e480a6"
      },
      {
        "src": "/images/optimized/ride-sharing-overview-640.webp",
        "width": 640,
        "height": 353,
        "bytes": 34512,
        "sha256": "1c0bb03c20c653a5c01d42d747d44d44f404878e8c45a2085e24d1fe46e11714"
      },
      {
        "src": "/images/optimized/ride-sharing-overview-768.webp",
        "width": 768,
        "height": 423,
        "bytes": 45594,
        "sha256": "0764d3db8ad63da76852ea3f8c5d9774a3194046d21d7598434aeefdd92277b8"
      },
      {
        "src": "/images/optimized/ride-sharing-overview-1024.webp",
        "width": 1024,
        "height": 564,
        "bytes": 69880,
        "sha256": "9390eff12467cd3b21f69180fe77154ea7e2e0746c80a6623a7e4078b0640be2"
      },
      {
        "src": "/images/optimized/ride-sharing-overview-1360.webp",
        "width": 1360,
        "height": 749,
        "bytes": 104790,
        "sha256": "d7d8984291097ddac013e4cda0dad416062aed91e9a61845ce5abe228a02933e"
      },
      {
        "src": "/images/optimized/ride-sharing-overview-1690.webp",
        "width": 1690,
        "height": 931,
        "bytes": 141310,
        "sha256": "cedbde39e906f0138771a8b592342dd8321964ad17fa6dd9c06be43d2c73a5a0"
      }
    ]
  },
  "/images/ride-sharing-people-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 1519954,
    "sha256": "2bd65947b44b7013e198b96bd914de5345b5547660931bec25bdf48e1b2e4e2e",
    "candidates": [
      {
        "src": "/images/optimized/ride-sharing-people-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 6672,
        "sha256": "49a5e627e5562d1e3dd73fb577fd895c6b023b68f1dc5d6e1b694d623380b03b"
      },
      {
        "src": "/images/optimized/ride-sharing-people-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 13712,
        "sha256": "2bc0831c3f7fdda2bfd59f0387a8880777592e1ed7efa40b909b4b3caf68d153"
      },
      {
        "src": "/images/optimized/ride-sharing-people-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 17502,
        "sha256": "20e4869fe44cc6d9bf322c91bc795c33e68c43e43175c5897c69d00ffef127c4"
      },
      {
        "src": "/images/optimized/ride-sharing-people-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 26302,
        "sha256": "3781f57b9dea466a85ca9b17674943c74b2fabcea047650215fc874c105ef6ef"
      },
      {
        "src": "/images/optimized/ride-sharing-people-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 38552,
        "sha256": "b345dc1b5073e34f669964e05559b191393b2a729adb9ba8875fbd2360bae9b3"
      },
      {
        "src": "/images/optimized/ride-sharing-people-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 45688,
        "sha256": "0809570cacb7d7a299a373b5bdea0513fe5d4cae165cc0dfd72325509bd73aa2"
      }
    ]
  },
  "/images/ride-sharing-ride-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 1597129,
    "sha256": "50a001de407def98f577f3308d5f5059edd0cac9409304536a146e83f5f22e65",
    "candidates": [
      {
        "src": "/images/optimized/ride-sharing-ride-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 9568,
        "sha256": "92465a69d95d4a104ccd38614cb6eeb01109bc038ac75b2c75044ada2e63e91b"
      },
      {
        "src": "/images/optimized/ride-sharing-ride-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 19676,
        "sha256": "02b42e8a7f92f896d505ce1c9494df940388fa1f3e53dba39813490796c3d5a4"
      },
      {
        "src": "/images/optimized/ride-sharing-ride-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 25036,
        "sha256": "3a2b55688e7b4c02fb9da4eb3d58404a01399d593c7ef4b24160b785a604652e"
      },
      {
        "src": "/images/optimized/ride-sharing-ride-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 38146,
        "sha256": "4f704bbb3277172ff158a73d18dda17a98356cefe5f8c2d29eba4e6fae10c699"
      },
      {
        "src": "/images/optimized/ride-sharing-ride-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 57274,
        "sha256": "e6ea6da7e294dcce8b048b90517d7355bf251fefd958a21b4639c0e1062f63a6"
      },
      {
        "src": "/images/optimized/ride-sharing-ride-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 68136,
        "sha256": "c0e5195460e594b42ada77ac9c46b7bc52b02d40f3a249d0b52066da01b31eff"
      }
    ]
  },
  "/images/ride-sharing-routing-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 1890827,
    "sha256": "d24611d7b7a150c03d7901e34a52c53a0ea95054f8d3c0acc2066a796bf15ad3",
    "candidates": [
      {
        "src": "/images/optimized/ride-sharing-routing-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 7640,
        "sha256": "af9f17d3fd14fd88ff206e0eb6420b4d7609ac797889e6aae4db5ee3bdc9e9b0"
      },
      {
        "src": "/images/optimized/ride-sharing-routing-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 16786,
        "sha256": "ee00da59dd29c0a55cf3f60dd7405edfd907c68f8ac8aeb9028e6a7bc27c30c3"
      },
      {
        "src": "/images/optimized/ride-sharing-routing-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 23068,
        "sha256": "59e6135b67a8eaa161baf34e474b7b1ea8d7c7ac754cde394abb037b557d6bed"
      },
      {
        "src": "/images/optimized/ride-sharing-routing-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 35494,
        "sha256": "ebffe4ddc3fa0350d0482ea061c9080f3446a1e34ba55e01a9fa12ae1f8ee2e8"
      },
      {
        "src": "/images/optimized/ride-sharing-routing-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 53990,
        "sha256": "d37ccb9fb262b31d74b189c54d757442ae8e536a3e1b13550f6accc97dff91bd"
      },
      {
        "src": "/images/optimized/ride-sharing-routing-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 65794,
        "sha256": "63023efcfbe8bae9a570955a53c19a52c5e5c4b21a685bca1f8d2201e4dd9580"
      }
    ]
  },
  "/images/ride-sharing-service-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2099885,
    "sha256": "688332f3853ac69836c1d293a3d8c8a96acd426f23e4ad621872345c655989fd",
    "candidates": [
      {
        "src": "/images/optimized/ride-sharing-service-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 9784,
        "sha256": "e026d6c2ccb426ad92d84750cc4143a9ddb761ab3153635ab4fde379e89945a1"
      },
      {
        "src": "/images/optimized/ride-sharing-service-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 20830,
        "sha256": "f79162d80454c22178d9e5023ae00d95144759cca52c8fa9a91c11d282377d4e"
      },
      {
        "src": "/images/optimized/ride-sharing-service-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 27548,
        "sha256": "6946211b7ed0dfb2091b6daffa16bac752006107ad0a438b79014d511fddc677"
      },
      {
        "src": "/images/optimized/ride-sharing-service-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 42514,
        "sha256": "d4ed72991d9672c52b245d45a6edd51a31838b63813bf73ed33dcdca8bf025a2"
      },
      {
        "src": "/images/optimized/ride-sharing-service-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 65680,
        "sha256": "5b49663e6c4b9d217f8675c5d6c03a95efcea0faef217de764b6cafeba246ec5"
      },
      {
        "src": "/images/optimized/ride-sharing-service-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 78614,
        "sha256": "5fdfa37f2b61bf6850d7454cd68f186f5af8a8ecd602a90629e25252d7170901"
      }
    ]
  },
  "/images/splitwise-entity-flow.png": {
    "width": 1774,
    "height": 887,
    "bytes": 1078727,
    "sha256": "8a0bd81d22b17a6139eac7cf79bf2728c62273c684426b01075b3873d5a5839e",
    "candidates": [
      {
        "src": "/images/optimized/splitwise-entity-flow-384.webp",
        "width": 384,
        "height": 192,
        "bytes": 8526,
        "sha256": "b584d16a7aee00882dad24d95cbf86e3103a5fc807483e27eb6d3a72cadaec06"
      },
      {
        "src": "/images/optimized/splitwise-entity-flow-640.webp",
        "width": 640,
        "height": 320,
        "bytes": 17340,
        "sha256": "58e99424436c260a27e2b43004281230d8e2d8c5361a51b3f5181e3bd420f3f4"
      },
      {
        "src": "/images/optimized/splitwise-entity-flow-768.webp",
        "width": 768,
        "height": 384,
        "bytes": 22166,
        "sha256": "82c45d1e3e92ccbbdbf9773b0ee6f15587bd9c5db20696d17004f9cb3d947b1a"
      },
      {
        "src": "/images/optimized/splitwise-entity-flow-1024.webp",
        "width": 1024,
        "height": 512,
        "bytes": 33780,
        "sha256": "9f981f432055996da6d8b2be2c4a65b863d34b37e73e4a02d99e7954b1fc056a"
      },
      {
        "src": "/images/optimized/splitwise-entity-flow-1360.webp",
        "width": 1360,
        "height": 680,
        "bytes": 49404,
        "sha256": "b001807c37ba985f827c4c96110f25da54be78c9b24432c7da7b9e2091d92c65"
      },
      {
        "src": "/images/optimized/splitwise-entity-flow-1774.webp",
        "width": 1774,
        "height": 887,
        "bytes": 68692,
        "sha256": "41a245ace66720868fd7e88f037ce106f86a0867b69811f22568151b5e311d97"
      }
    ]
  },
  "/images/splitwise-overview.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 1979861,
    "sha256": "2411f29206f18bca1d8b3a07d2437f8eb195dce47973966a38b00203eb6ba0df",
    "candidates": [
      {
        "src": "/images/optimized/splitwise-overview-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 20550,
        "sha256": "c11ed8915c70ed70e39b7232352cabe0440ca259a9fa2aba4dd2b10ab4fa00ca"
      },
      {
        "src": "/images/optimized/splitwise-overview-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 44498,
        "sha256": "b991d16b52f8ec25464de831d1cb6b021f9f18ea80564b5d127840f8bc52530b"
      },
      {
        "src": "/images/optimized/splitwise-overview-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 57330,
        "sha256": "8ba1902768ccb727b347032ab7b10f372304d2b1b02e8769a0e2561212cdd584"
      },
      {
        "src": "/images/optimized/splitwise-overview-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 88296,
        "sha256": "b421937d1e6f77b2fa040254953890a37d052ccc819c29d4e607a7e7d3f4baeb"
      },
      {
        "src": "/images/optimized/splitwise-overview-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 133840,
        "sha256": "2f47b17fc045d8aef229d5caf41398e8349630a2f35a4de0da6766b6db4d69fc"
      },
      {
        "src": "/images/optimized/splitwise-overview-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 159556,
        "sha256": "d7887f8a88bdf5edcb43898dc761483e045363e44b72567c7b1987644e6e9eeb"
      }
    ]
  },
  "/images/tic-tac-toe-board-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 1878842,
    "sha256": "04c15bde16300d568604ef9316dca4ab23d080afc26cdf590588283db9ddba3e",
    "candidates": [
      {
        "src": "/images/optimized/tic-tac-toe-board-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 13202,
        "sha256": "c2481d0334d1a8145567f03160e37f3f656a91e6da201a576bf122cd567004a6"
      },
      {
        "src": "/images/optimized/tic-tac-toe-board-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 27056,
        "sha256": "3ff2ec5eb6dc7f1d37e578e4b24c12b6a05fc390c30f85989bd30cdf382e7492"
      },
      {
        "src": "/images/optimized/tic-tac-toe-board-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 34358,
        "sha256": "20f8343b17c5a3d0cca78420aaedd67ba97fbeacd15ea9861fd5cb45c68b75e5"
      },
      {
        "src": "/images/optimized/tic-tac-toe-board-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 52046,
        "sha256": "a8774af909e871de27d2042cb3ccd5ab58f4d64b5f4289afd524bdf7e8be6f41"
      },
      {
        "src": "/images/optimized/tic-tac-toe-board-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 76668,
        "sha256": "88b256d88dc934841d6b763b01fbbde976892f1134eb82fdc27767958a203fd9"
      },
      {
        "src": "/images/optimized/tic-tac-toe-board-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 90920,
        "sha256": "5a634989521c6b8e5db7a747d7d9798354f938f0820fafcb0471c23b6cb525f3"
      }
    ]
  },
  "/images/tic-tac-toe-entity-flow.png": {
    "width": 1774,
    "height": 887,
    "bytes": 2074739,
    "sha256": "0b741daa546f5cb263812d450bbac59245f268da31136623e7e969eb06214978",
    "candidates": [
      {
        "src": "/images/optimized/tic-tac-toe-entity-flow-384.webp",
        "width": 384,
        "height": 192,
        "bytes": 9838,
        "sha256": "74b4493b980d3e2e901d63f2ebaf11bab7b176e62dc9bda56f93ee23dc60727e"
      },
      {
        "src": "/images/optimized/tic-tac-toe-entity-flow-640.webp",
        "width": 640,
        "height": 320,
        "bytes": 21330,
        "sha256": "19d0f4661dc4ead98b3cb8fd760c50fbe32553d0edc17181597bb0634bf572b5"
      },
      {
        "src": "/images/optimized/tic-tac-toe-entity-flow-768.webp",
        "width": 768,
        "height": 384,
        "bytes": 28382,
        "sha256": "8ba9e6771860ad09b6b64973e37af72126283962aaa3be7281fc14ab85ad39cf"
      },
      {
        "src": "/images/optimized/tic-tac-toe-entity-flow-1024.webp",
        "width": 1024,
        "height": 512,
        "bytes": 45318,
        "sha256": "b1bcf2f557634d549cb010be59ebeee875a0a82a584c5970df719ee31e175b0b"
      },
      {
        "src": "/images/optimized/tic-tac-toe-entity-flow-1360.webp",
        "width": 1360,
        "height": 680,
        "bytes": 72212,
        "sha256": "f4128a52c0623e4708a01c39f2dbe18f3086463d97d21e36e8e69abc6448001b"
      },
      {
        "src": "/images/optimized/tic-tac-toe-entity-flow-1774.webp",
        "width": 1774,
        "height": 887,
        "bytes": 113654,
        "sha256": "e2d6fd49cdfb0808dab0221be0bdf1294d7093199578795799b980d3a41de91a"
      }
    ]
  },
  "/images/tic-tac-toe-game-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 1765500,
    "sha256": "5d446fc3af218cb8647482b722ff5a45b3ff8922a9efd093dfec7955b9eaaede",
    "candidates": [
      {
        "src": "/images/optimized/tic-tac-toe-game-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 12920,
        "sha256": "38aece328d51382587630017ebde857311c52fa99ed3d891b86177f4a599fb10"
      },
      {
        "src": "/images/optimized/tic-tac-toe-game-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 27970,
        "sha256": "99d72b69564e3c2b0a43035c91248d89afea9ceef49ba2ab23dabea319223426"
      },
      {
        "src": "/images/optimized/tic-tac-toe-game-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 35454,
        "sha256": "b7098dfa5d7d7768c000ef362a9d2ac6c9e8fe146352cfeef5f6dd11fa71d355"
      },
      {
        "src": "/images/optimized/tic-tac-toe-game-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 52272,
        "sha256": "02f8382274a852e91f04e09c1fb086cbb67e5fe91c3dd74544ff9214d7c1e014"
      },
      {
        "src": "/images/optimized/tic-tac-toe-game-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 78430,
        "sha256": "b5b6bf9846bbf5403560df814760928e8cbf8d049bb8fcc3f42212e4c552657e"
      },
      {
        "src": "/images/optimized/tic-tac-toe-game-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 90458,
        "sha256": "5211fbcfb22b318d0bdfafe4d1ae099752b111e67c7c3617024a2303a83dd995"
      }
    ]
  },
  "/images/tic-tac-toe-player-class.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 1793238,
    "sha256": "410ee2b91cb715f8eeb2d13997ff32924a00139df7bfd408fc6a93e8cedcfa9c",
    "candidates": [
      {
        "src": "/images/optimized/tic-tac-toe-player-class-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 13168,
        "sha256": "79a752f1167191b713ec7a0efdd3169392bb18ea087f40b3b1a62d8cf6f46aba"
      },
      {
        "src": "/images/optimized/tic-tac-toe-player-class-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 26916,
        "sha256": "4eb8550470e63f816a6db57359503aadccaab7c349fd48c5a8cb5645e8c9abd8"
      },
      {
        "src": "/images/optimized/tic-tac-toe-player-class-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 34262,
        "sha256": "35ddbfa111fa5cb640516effeb71be569dea44154c55868a7f4a3669c8627a6d"
      },
      {
        "src": "/images/optimized/tic-tac-toe-player-class-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 50846,
        "sha256": "1511ddff8b58c3b3e1b6a851440fd9938f1b790fa7fb145f273766158bfd3b3e"
      },
      {
        "src": "/images/optimized/tic-tac-toe-player-class-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 73382,
        "sha256": "a22e488398f1f9f1aea462f6f7cc5ed3735245d427828fc391704e2ed719dd00"
      },
      {
        "src": "/images/optimized/tic-tac-toe-player-class-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 84780,
        "sha256": "977451e8220f226485c99f64df7d0d4efd18b20d8a181fc2a084b93aa8c7471e"
      }
    ]
  },
  "/images/tic-tac-toe-turn-flow.png": {
    "width": 1536,
    "height": 1024,
    "bytes": 2276712,
    "sha256": "4b9df5839ea81c1f9f565e1f38f477672ebceb5186901497033a060acc9ad204",
    "candidates": [
      {
        "src": "/images/optimized/tic-tac-toe-turn-flow-384.webp",
        "width": 384,
        "height": 256,
        "bytes": 12998,
        "sha256": "0a092d6f9ea3e45d664df4522a5fedc039b5777e0c2cbf08be5871be40ed85c4"
      },
      {
        "src": "/images/optimized/tic-tac-toe-turn-flow-640.webp",
        "width": 640,
        "height": 427,
        "bytes": 28466,
        "sha256": "9b0f4ae732ce8c128425e49222c9b4f14301d727c8f4cfcd35c8bd6c8cf1aa5f"
      },
      {
        "src": "/images/optimized/tic-tac-toe-turn-flow-768.webp",
        "width": 768,
        "height": 512,
        "bytes": 38650,
        "sha256": "862aad811e9f28f7081ac4277572fc87704e2c93ba917c2d2aff525c1255fa88"
      },
      {
        "src": "/images/optimized/tic-tac-toe-turn-flow-1024.webp",
        "width": 1024,
        "height": 683,
        "bytes": 61846,
        "sha256": "446964d84350d74e75bfe8bba7067b04f1b2958bbb94d9f756f3f7924734c831"
      },
      {
        "src": "/images/optimized/tic-tac-toe-turn-flow-1360.webp",
        "width": 1360,
        "height": 907,
        "bytes": 96230,
        "sha256": "149bbb3f98f51060ff7f71ea3faa51b341bf6c7ac19c5c36b52b4631369c83dc"
      },
      {
        "src": "/images/optimized/tic-tac-toe-turn-flow-1536.webp",
        "width": 1536,
        "height": 1024,
        "bytes": 119576,
        "sha256": "0c4c38c09ee07551fca74b36300bbb1184bba8d23c5df310e26ebc5cb2674c6a"
      }
    ]
  }
};
