export type LearningPhase = "start" | "requirements" | "entities" | "class-design" | "implementation" | "extensions";

export type LearningStep = {
  id: string;
  legacyIds?: string[];
  phase: LearningPhase;
  title: string;
  eyebrow: string;
  minutes: number;
};

export const learningPhaseLabels: Record<LearningPhase, string> = {
  start: "Start",
  requirements: "Requirements",
  entities: "Entities",
  "class-design": "Class design",
  implementation: "Implementation",
  extensions: "Extensions",
};

export const ticTacToeLearningSteps: LearningStep[] = [
  { id: "orientation", phase: "start", title: "See the game loop", eyebrow: "Mental model", minutes: 1 },
  { id: "framework", phase: "start", title: "Use the five-phase method", eyebrow: "Reusable interview path", minutes: 1 },
  { id: "interview-dynamics", phase: "start", title: "Navigate the interview", eyebrow: "Time, talk, and signals", minutes: 2 },
  { id: "orientation-check", phase: "start", title: "Know what to clarify first", eyebrow: "Think before classes", minutes: 1 },
  { id: "incomplete-prompt", phase: "requirements", title: "Find what the prompt omits", eyebrow: "Incomplete prompt", minutes: 1 },
  { id: "requirements-dialogue", phase: "requirements", title: "Practice the interview dialogue", eyebrow: "Ask, listen, confirm", minutes: 1 },
  { id: "question-groups", phase: "requirements", title: "Choose the questions to ask", eyebrow: "Question checklist", minutes: 2 },
  { id: "players-and-marks", phase: "requirements", title: "Review the interviewer answers", eyebrow: "Question and answer", minutes: 2 },
  { id: "confirmed-spec", phase: "requirements", title: "Confirm the specification", eyebrow: "Agreed requirements", minutes: 1 },
  { id: "entity-transition", phase: "entities", title: "Discover the entities", eyebrow: "From requirements to objects", minutes: 1 },
  { id: "modeling-vocabulary", phase: "entities", title: "Learn the four modeling choices", eyebrow: "Class, enum, field, or leave out", minutes: 2 },
  { id: "entity-intro", phase: "entities", title: "Choose the classes", eyebrow: "Class candidates", minutes: 2 },
  { id: "cell-question", phase: "entities", title: "Model the remaining values", eyebrow: "Classes, fields, and enums", minutes: 2 },
  { id: "ownership-rule", phase: "entities", title: "Assign each rule an owner", eyebrow: "Responsibility check", minutes: 2 },
  { id: "entity-flow", phase: "entities", title: "Build the final entity flow", eyebrow: "Flow challenge", minutes: 2 },
  { id: "entity-summary", phase: "entities", title: "Review the final entity model", eyebrow: "Entity checkpoint", minutes: 1 },
  { id: "design-principles", phase: "class-design", title: "Learn the principles through failures", eyebrow: "Problems before names", minutes: 2 },
  { id: "game-design-intro", phase: "class-design", title: "How to design a class", eyebrow: "Class design method", minutes: 1 },
  { id: "pattern-future", phase: "class-design", title: "Design Player", eyebrow: "Immutable identity", minutes: 2 },
  { id: "board-design", phase: "class-design", title: "Design Board", eyebrow: "Encapsulate the grid", minutes: 2 },
  { id: "game-design", phase: "class-design", title: "Derive Game state", eyebrow: "Match-flow state", minutes: 2 },
  { id: "game-design-two", phase: "class-design", title: "Derive Game behavior and API", eyebrow: "Public boundary", minutes: 2 },
  { id: "board-design-two", phase: "class-design", title: "Apply the design tools", eyebrow: "Principles by class", minutes: 2 },
  { id: "pattern-decisions", phase: "class-design", title: "Know when patterns are unnecessary", eyebrow: "Pattern restraint", minutes: 2 },
  { id: "pattern-check", phase: "class-design", title: "Review the final class blueprint", eyebrow: "Design checkpoint", minutes: 1 },
  { id: "implementation-map", legacyIds: ["implementation-flow"], phase: "implementation", title: "Map the code responsibilities", eyebrow: "From design to code", minutes: 1 },
  { id: "validation-order", phase: "implementation", title: "Order one safe move", eyebrow: "Interactive workflow", minutes: 2 },
  { id: "ownership-concept", legacyIds: ["enum-concept", "pattern-concept"], phase: "implementation", title: "Review the implementation concepts", eyebrow: "Four ideas in context", minutes: 2 },
  { id: "value-types", phase: "implementation", title: "Read the three value types", eyebrow: "Java code", minutes: 1 },
  { id: "move-result-check", phase: "implementation", title: "Model expected move failures", eyebrow: "API semantics", minutes: 1 },
  { id: "player-code", phase: "implementation", title: "Keep Player immutable", eyebrow: "Java code", minutes: 2 },
  { id: "validation-rule", phase: "implementation", title: "Predict what Board must protect", eyebrow: "Before Board.java", minutes: 2 },
  { id: "board-placement-code", legacyIds: ["board-win-code", "board-support-code"], phase: "implementation", title: "Read Board by responsibility", eyebrow: "Tabbed Board.java", minutes: 3 },
  { id: "game-overview", phase: "implementation", title: "Predict the Game workflow", eyebrow: "Before Game.java", minutes: 2 },
  { id: "game-setup-code", legacyIds: ["game-guards-code", "game-result-code", "game-support-code"], phase: "implementation", title: "Read Game by responsibility", eyebrow: "Tabbed Game.java", minutes: 3 },
  { id: "demo-code", phase: "implementation", title: "Use the public API", eyebrow: "TicTacToeDemo.java", minutes: 2 },
  { id: "scenario-happy", phase: "implementation", title: "Trace a complete win", eyebrow: "Scenario proof", minutes: 2 },
  { id: "scenario-check", legacyIds: ["scenario-rejection"], phase: "implementation", title: "Prove rejection changes nothing", eyebrow: "Invariant check", minutes: 2 },
  { id: "simulator-lab", phase: "implementation", title: "Challenge the model", eyebrow: "Interactive lab", minutes: 3 },
  { id: "extension-strategies", phase: "extensions", title: "Add computer move strategies", eyebrow: "Changed requirement", minutes: 2 },
  { id: "extension-board", phase: "extensions", title: "Generalize the board and win rule", eyebrow: "Changed requirement", minutes: 1 },
  { id: "extension-state", phase: "extensions", title: "Extend history and coordination", eyebrow: "Changed requirements", minutes: 2 },
  { id: "extension-answer", phase: "extensions", title: "Explain the design aloud", eyebrow: "Interview response", minutes: 1 },
  { id: "extensions-check", phase: "extensions", title: "Choose the smallest extension", eyebrow: "Final check", minutes: 1 },
];

export const parkingLotLearningSteps: LearningStep[] = [
  { id: "parking-orientation", phase: "start", title: "See the parking workflow", eyebrow: "Mental model", minutes: 1 },
  { id: "parking-framework", phase: "start", title: "Use the five-phase method", eyebrow: "Interview path", minutes: 1 },
  { id: "parking-interview", phase: "start", title: "Navigate the interview", eyebrow: "Time and signals", minutes: 2 },
  { id: "parking-orientation-check", phase: "start", title: "Know what to clarify first", eyebrow: "Before classes", minutes: 1 },
  { id: "parking-incomplete", phase: "requirements", title: "Find what the prompt omits", eyebrow: "Incomplete prompt", minutes: 1 },
  { id: "parking-dialogue", phase: "requirements", title: "Practice the interview dialogue", eyebrow: "Define nearest", minutes: 1 },
  { id: "parking-questions", phase: "requirements", title: "Choose the useful questions", eyebrow: "Clarify scope", minutes: 2 },
  { id: "parking-answers", phase: "requirements", title: "Review the interviewer answers", eyebrow: "Confirmed answers", minutes: 2 },
  { id: "parking-spec", phase: "requirements", title: "Confirm the specification", eyebrow: "Agreed scope", minutes: 1 },
  { id: "parking-entity-transition", phase: "entities", title: "Discover the candidate objects", eyebrow: "Nouns to models", minutes: 1 },
  { id: "parking-modeling-vocabulary", phase: "entities", title: "Learn the modeling choices", eyebrow: "Six choices", minutes: 2 },
  { id: "parking-classes", phase: "entities", title: "Choose the real classes", eyebrow: "Class candidates", minutes: 2 },
  { id: "parking-values", phase: "entities", title: "Model the remaining concepts", eyebrow: "Interface and values", minutes: 2 },
  { id: "parking-ownership", phase: "entities", title: "Assign each rule an owner", eyebrow: "Information ownership", minutes: 2 },
  { id: "parking-entity-flow", phase: "entities", title: "Build the entry flow", eyebrow: "Flow challenge", minutes: 2 },
  { id: "parking-entity-summary", phase: "entities", title: "Review the final entity model", eyebrow: "Entity checkpoint", minutes: 1 },
  { id: "parking-principles", phase: "class-design", title: "Learn principles through failures", eyebrow: "Problems before names", minutes: 2 },
  { id: "parking-design-method", phase: "class-design", title: "Learn the class-design sequence", eyebrow: "Repeatable method", minutes: 1 },
  { id: "parking-immutable-values", phase: "class-design", title: "Design the immutable values", eyebrow: "Java records", minutes: 2 },
  { id: "parking-spot-design", phase: "class-design", title: "Design ParkingSpot", eyebrow: "Own availability", minutes: 2 },
  { id: "parking-floor-design", phase: "class-design", title: "Design ParkingFloor", eyebrow: "Group spots", minutes: 2 },
  { id: "parking-lot-state", phase: "class-design", title: "Derive ParkingLot state", eyebrow: "Workflow memory", minutes: 2 },
  { id: "parking-lot-api", phase: "class-design", title: "Derive ParkingLot behavior and API", eyebrow: "Public boundary", minutes: 2 },
  { id: "parking-allocation", phase: "class-design", title: "Understand deterministic allocation", eyebrow: "Ordering rule", minutes: 2 },
  { id: "parking-patterns", phase: "class-design", title: "Use Strategy where behavior varies", eyebrow: "Pattern discipline", minutes: 2 },
  { id: "parking-blueprint", phase: "class-design", title: "Review the final class blueprint", eyebrow: "Design checkpoint", minutes: 2 },
  { id: "parking-code-map", phase: "implementation", title: "Map the code responsibilities", eyebrow: "Design to code", minutes: 1 },
  { id: "parking-order", phase: "implementation", title: "Order a safe parking request", eyebrow: "Mutation order", minutes: 2 },
  { id: "parking-code-concepts", phase: "implementation", title: "Review implementation concepts", eyebrow: "Java concepts", minutes: 2 },
  { id: "parking-enums", phase: "implementation", title: "Read the fixed value enums", eyebrow: "Java code", minutes: 2 },
  { id: "parking-records", phase: "implementation", title: "Read the immutable records", eyebrow: "Tabbed Java", minutes: 3 },
  { id: "parking-spot-predict", phase: "implementation", title: "Predict Spot and Floor behavior", eyebrow: "Before code", minutes: 2 },
  { id: "parking-spot-code", phase: "implementation", title: "Read Spot and Floor code", eyebrow: "Tabbed Java", minutes: 3 },
  { id: "parking-strategy-predict", phase: "implementation", title: "Predict the assignment algorithm", eyebrow: "Selection trace", minutes: 2 },
  { id: "parking-strategy-code", phase: "implementation", title: "Read the Strategy implementation", eyebrow: "Tabbed Java", minutes: 3 },
  { id: "parking-lot-predict", phase: "implementation", title: "Predict the ParkingLot workflow", eyebrow: "Before code", minutes: 2 },
  { id: "parking-lot-code", phase: "implementation", title: "Read ParkingLot by responsibility", eyebrow: "Tabbed Java", minutes: 3 },
  { id: "parking-demo", phase: "implementation", title: "Use the public API", eyebrow: "Demo code", minutes: 2 },
  { id: "parking-success", phase: "implementation", title: "Trace a successful allocation", eyebrow: "Scenario proof", minutes: 2 },
  { id: "parking-rejections", phase: "implementation", title: "Prove rejection changes nothing", eyebrow: "Invariant proof", minutes: 2 },
  { id: "parking-simulator", phase: "implementation", title: "Challenge the model", eyebrow: "Interactive lab", minutes: 3 },
  { id: "parking-concurrency", phase: "extensions", title: "Handle concurrent entrances", eyebrow: "Changed requirement", minutes: 2 },
  { id: "parking-capabilities", phase: "extensions", title: "Add capabilities without mixing rules", eyebrow: "Small changes", minutes: 2 },
  { id: "parking-reservations", phase: "extensions", title: "Introduce reservation states", eyebrow: "State transitions", minutes: 2 },
  { id: "parking-extension-answer", phase: "extensions", title: "Explain an extension aloud", eyebrow: "Interview response", minutes: 1 },
  { id: "parking-close", phase: "extensions", title: "Choose the smallest change and close", eyebrow: "Final check", minutes: 1 },
];

export const movieTicketBookingLearningSteps: LearningStep[] = [
  { id: "movie-orientation", phase: "start", title: "See the booking conflict", eyebrow: "Mental model", minutes: 1 },
  { id: "movie-framework", phase: "start", title: "Use the five-phase method", eyebrow: "Interview path", minutes: 1 },
  { id: "movie-interview", phase: "start", title: "Navigate the interview", eyebrow: "Time and signals", minutes: 2 },
  { id: "movie-orientation-check", phase: "start", title: "Know what to clarify first", eyebrow: "Before classes", minutes: 1 },
  { id: "movie-incomplete", phase: "requirements", title: "Find what the prompt omits", eyebrow: "Incomplete prompt", minutes: 1 },
  { id: "movie-dialogue", phase: "requirements", title: "Practice the interview dialogue", eyebrow: "Define booking", minutes: 1 },
  { id: "movie-questions", phase: "requirements", title: "Choose useful questions", eyebrow: "Clarify correctness", minutes: 2 },
  { id: "movie-answers", phase: "requirements", title: "Review the confirmed answers", eyebrow: "Confirmed rules", minutes: 2 },
  { id: "movie-spec", phase: "requirements", title: "Confirm the specification", eyebrow: "Agreed scope", minutes: 1 },
  { id: "movie-entity-transition", phase: "entities", title: "Discover candidate objects", eyebrow: "Nouns to models", minutes: 1 },
  { id: "movie-modeling-vocabulary", phase: "entities", title: "Learn the modeling choices", eyebrow: "Choose the smallest model", minutes: 2 },
  { id: "movie-classes", phase: "entities", title: "Choose the real classes", eyebrow: "Class candidates", minutes: 2 },
  { id: "movie-values", phase: "entities", title: "Model remaining concepts", eyebrow: "Enums, values, and fields", minutes: 2 },
  { id: "movie-ownership", phase: "entities", title: "Assign each rule an owner", eyebrow: "Information ownership", minutes: 2 },
  { id: "movie-entity-flow", phase: "entities", title: "Build the hold flow", eyebrow: "Flow challenge", minutes: 2 },
  { id: "movie-entity-summary", phase: "entities", title: "Review the final entity model", eyebrow: "Entity checkpoint", minutes: 1 },
  { id: "movie-principles", phase: "class-design", title: "Learn principles through failures", eyebrow: "Problems before names", minutes: 2 },
  { id: "movie-design-method", phase: "class-design", title: "Learn the class-design sequence", eyebrow: "Repeatable method", minutes: 1 },
  { id: "movie-immutable-values", phase: "class-design", title: "Design immutable values", eyebrow: "Stable facts", minutes: 2 },
  { id: "movie-physical-state", phase: "class-design", title: "Separate layout from show state", eyebrow: "Two meanings of seat", minutes: 2 },
  { id: "movie-show-seat-design", phase: "class-design", title: "Design ShowSeat", eyebrow: "Own one lifecycle", minutes: 2 },
  { id: "movie-show-design", phase: "class-design", title: "Design Show", eyebrow: "Protect the group", minutes: 2 },
  { id: "movie-service-state", phase: "class-design", title: "Derive BookingService state", eyebrow: "Workflow memory", minutes: 2 },
  { id: "movie-service-api", phase: "class-design", title: "Derive BookingService API", eyebrow: "Public boundary", minutes: 2 },
  { id: "movie-state-machine", phase: "class-design", title: "Build the seat state machine", eyebrow: "Legal transitions", minutes: 2 },
  { id: "movie-atomic-group", phase: "class-design", title: "Protect an all-or-nothing group", eyebrow: "Two-pass rule", minutes: 2 },
  { id: "movie-race", phase: "class-design", title: "Reproduce the race condition", eyebrow: "Unsafe interleaving", minutes: 2 },
  { id: "movie-critical-section", phase: "class-design", title: "Define the critical section", eyebrow: "One protected unit", minutes: 2 },
  { id: "movie-lock-boundary", phase: "class-design", title: "Choose the lock boundary", eyebrow: "Concurrency trade-off", minutes: 2 },
  { id: "movie-blueprint", phase: "class-design", title: "Review patterns and the blueprint", eyebrow: "Design checkpoint", minutes: 2 },
  { id: "movie-code-map", phase: "implementation", title: "Map code responsibilities", eyebrow: "Design to code", minutes: 1 },
  { id: "movie-hold-order", phase: "implementation", title: "Order a safe hold request", eyebrow: "Guard and mutation order", minutes: 2 },
  { id: "movie-code-concepts", phase: "implementation", title: "Review implementation concepts", eyebrow: "Java concurrency tools", minutes: 2 },
  { id: "movie-enums", phase: "implementation", title: "Read states and named results", eyebrow: "Java code", minutes: 2 },
  { id: "movie-records", phase: "implementation", title: "Read immutable records", eyebrow: "Tabbed Java", minutes: 3 },
  { id: "movie-physical-code", phase: "implementation", title: "Read the physical model", eyebrow: "Tabbed Java", minutes: 2 },
  { id: "movie-show-seat-predict", phase: "implementation", title: "Predict ShowSeat behavior", eyebrow: "Before code", minutes: 2 },
  { id: "movie-show-seat-code", phase: "implementation", title: "Read ShowSeat code", eyebrow: "Tabbed Java", minutes: 3 },
  { id: "movie-try-hold-predict", phase: "implementation", title: "Predict Show.tryHold", eyebrow: "Before code", minutes: 2 },
  { id: "movie-try-hold-code", phase: "implementation", title: "Read Show setup and tryHold", eyebrow: "Tabbed Java", minutes: 3 },
  { id: "movie-confirm-predict", phase: "implementation", title: "Predict confirmation and expiry", eyebrow: "State outcomes", minutes: 2 },
  { id: "movie-confirm-code", phase: "implementation", title: "Read confirmation and snapshots", eyebrow: "Tabbed Java", minutes: 3 },
  { id: "movie-service-predict", phase: "implementation", title: "Predict BookingService workflow", eyebrow: "Coordination boundary", minutes: 2 },
  { id: "movie-service-code", phase: "implementation", title: "Read BookingService by responsibility", eyebrow: "Tabbed Java", minutes: 3 },
  { id: "movie-concurrency-demo", phase: "implementation", title: "Prove concurrency deterministically", eyebrow: "Public API and race test", minutes: 3 },
  { id: "movie-simulator", phase: "implementation", title: "Challenge the model", eyebrow: "Interactive lab", minutes: 3 },
  { id: "movie-payment", phase: "extensions", title: "Add real payment safely", eyebrow: "Changed requirement", minutes: 2 },
  { id: "movie-distributed", phase: "extensions", title: "Move to several application servers", eyebrow: "Shared authority", minutes: 2 },
  { id: "movie-expiry-scale", phase: "extensions", title: "Scale hold expiry", eyebrow: "Efficient cleanup", minutes: 2 },
  { id: "movie-extension-answer", phase: "extensions", title: "Explain concurrency aloud", eyebrow: "Interview response", minutes: 1 },
  { id: "movie-close", phase: "extensions", title: "Choose the smallest extension and close", eyebrow: "Final check", minutes: 1 },
];

export const notificationSystemLearningSteps: LearningStep[] = [
  { id: "notification-orientation", phase: "start", title: "See the notification workflow", eyebrow: "Mental model", minutes: 1 },
  { id: "notification-framework", phase: "start", title: "Use the five-phase method", eyebrow: "Interview path", minutes: 1 },
  { id: "notification-interview", phase: "start", title: "Navigate the interview", eyebrow: "Time and signals", minutes: 2 },
  { id: "notification-orientation-check", phase: "start", title: "Know what to clarify first", eyebrow: "Before classes", minutes: 1 },
  { id: "notification-incomplete", phase: "requirements", title: "Find what the prompt omits", eyebrow: "Incomplete prompt", minutes: 1 },
  { id: "notification-dialogue", phase: "requirements", title: "Practice the interview dialogue", eyebrow: "Define send", minutes: 1 },
  { id: "notification-questions", phase: "requirements", title: "Choose useful questions", eyebrow: "Clarify delivery", minutes: 2 },
  { id: "notification-answers", phase: "requirements", title: "Review the confirmed answers", eyebrow: "Confirmed rules", minutes: 2 },
  { id: "notification-spec", phase: "requirements", title: "Confirm the specification", eyebrow: "Agreed scope", minutes: 1 },
  { id: "notification-entity-transition", phase: "entities", title: "Discover candidate objects", eyebrow: "Nouns to models", minutes: 1 },
  { id: "notification-modeling-vocabulary", phase: "entities", title: "Learn the modeling choices", eyebrow: "Choose the smallest model", minutes: 2 },
  { id: "notification-types", phase: "entities", title: "Choose the real types", eyebrow: "Type candidates", minutes: 2 },
  { id: "notification-values", phase: "entities", title: "Model remaining concepts", eyebrow: "Enums, values, and fields", minutes: 2 },
  { id: "notification-ownership", phase: "entities", title: "Assign each rule an owner", eyebrow: "Information ownership", minutes: 2 },
  { id: "notification-entity-flow", phase: "entities", title: "Build the delivery flow", eyebrow: "Flow challenge", minutes: 2 },
  { id: "notification-entity-summary", phase: "entities", title: "Review the final entity model", eyebrow: "Entity checkpoint", minutes: 1 },
  { id: "notification-principles", phase: "class-design", title: "Learn principles through failures", eyebrow: "Problems before names", minutes: 2 },
  { id: "notification-design-method", phase: "class-design", title: "Learn the class-design sequence", eyebrow: "Repeatable method", minutes: 1 },
  { id: "notification-request-design", phase: "class-design", title: "Design NotificationRequest", eyebrow: "Immutable input", minutes: 2 },
  { id: "notification-sender-design", phase: "class-design", title: "Design channel senders", eyebrow: "Replaceable behavior", minutes: 2 },
  { id: "notification-retry-design", phase: "class-design", title: "Design RetryPolicy", eyebrow: "Bound retries", minutes: 2 },
  { id: "notification-job-design", phase: "class-design", title: "Design DeliveryJob", eyebrow: "Thread-safe state", minutes: 2 },
  { id: "notification-state-machine", phase: "class-design", title: "Build the job state machine", eyebrow: "Legal transitions", minutes: 2 },
  { id: "notification-service-state", phase: "class-design", title: "Derive NotificationService state", eyebrow: "Workflow memory", minutes: 2 },
  { id: "notification-service-api", phase: "class-design", title: "Derive NotificationService API", eyebrow: "Public boundary", minutes: 2 },
  { id: "notification-thread-safety", phase: "class-design", title: "Protect concurrent job state", eyebrow: "Visibility and ownership", minutes: 2 },
  { id: "notification-executor-ownership", phase: "class-design", title: "Understand executor ownership", eyebrow: "Lifecycle boundary", minutes: 2 },
  { id: "notification-blueprint", phase: "class-design", title: "Review patterns and the blueprint", eyebrow: "Design checkpoint", minutes: 2 },
  { id: "notification-code-map", phase: "implementation", title: "Map responsibilities to Java", eyebrow: "Design to code", minutes: 1 },
  { id: "notification-submit-order", phase: "implementation", title: "Order safe asynchronous submission", eyebrow: "Submission order", minutes: 2 },
  { id: "notification-code-concepts", phase: "implementation", title: "Review implementation concepts", eyebrow: "Java concurrency tools", minutes: 2 },
  { id: "notification-enums", phase: "implementation", title: "Read channels and delivery states", eyebrow: "Java code", minutes: 2 },
  { id: "notification-records", phase: "implementation", title: "Read immutable request and results", eyebrow: "Tabbed Java", minutes: 3 },
  { id: "notification-sender-predict", phase: "implementation", title: "Predict sender behavior", eyebrow: "Before code", minutes: 2 },
  { id: "notification-sender-code", phase: "implementation", title: "Read the sender strategies", eyebrow: "Tabbed Java", minutes: 3 },
  { id: "notification-job-predict", phase: "implementation", title: "Predict DeliveryJob transitions", eyebrow: "Before code", minutes: 2 },
  { id: "notification-job-code", phase: "implementation", title: "Read DeliveryJob", eyebrow: "Thread-safe Java", minutes: 3 },
  { id: "notification-submit-predict", phase: "implementation", title: "Predict submission behavior", eyebrow: "Before service code", minutes: 2 },
  { id: "notification-submit-code", phase: "implementation", title: "Read construction and submission", eyebrow: "Tabbed Java", minutes: 3 },
  { id: "notification-retry-predict", phase: "implementation", title: "Predict the retry loop", eyebrow: "Attempt outcomes", minutes: 2 },
  { id: "notification-delivery-code", phase: "implementation", title: "Read complete delivery execution", eyebrow: "Worker code", minutes: 3 },
  { id: "notification-lifecycle-code", phase: "implementation", title: "Read status and lifecycle methods", eyebrow: "Safe reads and shutdown", minutes: 2 },
  { id: "notification-async-proof", phase: "implementation", title: "Prove asynchronous behavior", eyebrow: "Deterministic test", minutes: 2 },
  { id: "notification-parallel-proof", phase: "implementation", title: "Prove parallel execution and retries", eyebrow: "Deterministic test", minutes: 3 },
  { id: "notification-demo", phase: "implementation", title: "Use the public API", eyebrow: "Demo code", minutes: 2 },
  { id: "notification-simulator", phase: "implementation", title: "Challenge the model", eyebrow: "Interactive lab", minutes: 3 },
  { id: "notification-durable", phase: "extensions", title: "Move from threads to durable delivery", eyebrow: "Changed boundary", minutes: 2 },
  { id: "notification-close", phase: "extensions", title: "Add production capabilities and close", eyebrow: "Interview response", minutes: 2 },
];

export const meetingRoomSchedulerLearningSteps: LearningStep[] = [
  ...[
    ["meeting-orientation","start","See the scheduling decision","Mental model",1],
    ["meeting-framework","start","Use the five-phase method","Interview path",1],
    ["meeting-interview","start","Navigate the interview","Time and signals",2],
    ["meeting-orientation-check","start","Know what to clarify first","Before classes",1],
    ["meeting-incomplete","requirements","Find what the prompt omits","Incomplete prompt",1],
    ["meeting-dialogue","requirements","Practice the interview dialogue","Define conflict",1],
    ["meeting-questions","requirements","Choose useful questions","Clarify correctness",2],
    ["meeting-answers","requirements","Review the confirmed answers","Confirmed rules",2],
    ["meeting-spec","requirements","Confirm the specification","Agreed scope",1],
    ["meeting-entity-transition","entities","Discover candidate objects","Nouns to models",1],
    ["meeting-modeling-vocabulary","entities","Learn the modeling choices","Choose the smallest model",2],
    ["meeting-types","entities","Choose the real types","Class candidates",2],
    ["meeting-values","entities","Model the remaining concepts","Enums, values, and fields",2],
    ["meeting-ownership","entities","Assign each rule an owner","Information ownership",2],
    ["meeting-entity-flow","entities","Build the scheduling flow","Flow challenge",2],
    ["meeting-entity-summary","entities","Review the final entity model","Entity checkpoint",1],
    ["meeting-principles","class-design","Learn principles through failures","Problems before names",2],
    ["meeting-design-method","class-design","Learn the class-design sequence","Repeatable method",1],
    ["meeting-immutable-values","class-design","Design immutable request values","Stable facts",2],
    ["meeting-half-open","class-design","Understand half-open intervals","Boundary rule",2],
    ["meeting-overlap-practice","class-design","Practice the overlap rule","Interval exercise",2],
    ["meeting-room-design","class-design","Design Room","Own one schedule",2],
    ["meeting-invariant","class-design","Build the schedule invariant","Protected promise",2],
    ["meeting-neighbours","class-design","Find the two relevant neighbours","TreeMap reasoning",2],
    ["meeting-complexity","class-design","Understand complexity and alternatives","Trade-offs",2],
    ["meeting-strategy-design","class-design","Design the selection Strategy","Replaceable policy",2],
    ["meeting-scheduler-design","class-design","Design MeetingScheduler","Workflow boundary",2],
    ["meeting-blueprint","class-design","Review patterns and the final blueprint","Design checkpoint",2],
    ["meeting-code-map","implementation","Map responsibilities to Java","Design to code",1],
    ["meeting-schedule-order","implementation","Order a safe schedule request","Mutation order",2],
    ["meeting-code-concepts","implementation","Review implementation concepts","Java tools",2],
    ["meeting-enums","implementation","Read enums and named results","Java code",2],
    ["meeting-records","implementation","Read immutable meeting values","Tabbed Java",3],
    ["meeting-timeslot-predict","implementation","Predict TimeSlot behavior","Before code",2],
    ["meeting-timeslot-code","implementation","Verify the TimeSlot implementation","Complete method",2],
    ["meeting-room-availability-predict","implementation","Predict Room availability","Neighbour lookup",2],
    ["meeting-room-setup-code","implementation","Read Room construction and suitability","Tabbed Java",3],
    ["meeting-room-availability-code","implementation","Read Room availability and mutation","Tabbed Java",3],
    ["meeting-selection-predict","implementation","Predict deterministic selection","Selection trace",2],
    ["meeting-strategy-code","implementation","Read the Strategy implementation","Complete method",3],
    ["meeting-scheduler-predict","implementation","Predict the Scheduler workflow","Before code",2],
    ["meeting-scheduler-code","implementation","Read MeetingScheduler by responsibility","Tabbed Java",3],
    ["meeting-demo","implementation","Use the public API","Demo code",2],
    ["meeting-success-trace","implementation","Trace a successful boundary request","Scenario proof",2],
    ["meeting-rejection-proof","implementation","Prove rejection changes nothing","Invariant proof",2],
    ["meeting-simulator","implementation","Challenge the model","Interactive lab",3],
    ["meeting-rule-extensions","extensions","Change the scheduling rules","Changed requirements",2],
    ["meeting-concurrency-close","extensions","Handle concurrency and close","Interview response",2],
  ].map(([id, phase, title, eyebrow, minutes]) => ({ id, phase, title, eyebrow, minutes } as LearningStep)),
];
