export type LearningPhase = "start" | "requirements" | "entities" | "class-design" | "implementation" | "extensions";

export type LearningStep = {
  id: string;
  phase: LearningPhase;
  title: string;
  eyebrow: string;
  minutes: number;
};

export const learningPhaseLabels: Record<LearningPhase, string> = {
  start: "Start",
  requirements: "Requirements",
  entities: "Entities",
  "class-design": "Class design",
  implementation: "Implementation",
  extensions: "Extensions",
};

export const ticTacToeLearningSteps: LearningStep[] = [
  { id: "orientation", phase: "start", title: "See the game loop", eyebrow: "Mental model", minutes: 1 },
  { id: "framework", phase: "start", title: "Use the five-phase method", eyebrow: "Reusable interview path", minutes: 1 },
  { id: "orientation-check", phase: "start", title: "Know what to clarify first", eyebrow: "Think before classes", minutes: 1 },
  { id: "incomplete-prompt", phase: "requirements", title: "Find what the prompt omits", eyebrow: "Incomplete prompt", minutes: 1 },
  { id: "question-groups", phase: "requirements", title: "Ask four kinds of questions", eyebrow: "Requirements toolkit", minutes: 1 },
  { id: "players-question", phase: "requirements", title: "Predict what creates currentPlayer", eyebrow: "Test your reasoning", minutes: 1 },
  { id: "players-and-marks", phase: "requirements", title: "Confirm players and the first turn", eyebrow: "Turn answers into state", minutes: 1 },
  { id: "board-and-win", phase: "requirements", title: "Define the board and a win", eyebrow: "Make rules precise", minutes: 1 },
  { id: "winning-cell", phase: "requirements", title: "Complete a winning line", eyebrow: "Visual challenge", minutes: 1 },
  { id: "completion-rule", phase: "requirements", title: "Define when play stops", eyebrow: "Completion states", minutes: 1 },
  { id: "invalid-reasoning", phase: "requirements", title: "Predict rejection behavior", eyebrow: "Protect state", minutes: 1 },
  { id: "invalid-actions", phase: "requirements", title: "Name every rejected move", eyebrow: "Observable errors", minutes: 1 },
  { id: "scope-boundaries", phase: "requirements", title: "Keep the first version small", eyebrow: "Scope boundary", minutes: 1 },
  { id: "confirmed-spec", phase: "requirements", title: "Read back the contract", eyebrow: "Requirements checkpoint", minutes: 2 },
  { id: "requirements-check", phase: "requirements", title: "Are the requirements ready?", eyebrow: "Checkpoint", minutes: 1 },
  { id: "entity-intro", phase: "entities", title: "Extract candidates without guessing", eyebrow: "Discover entities", minutes: 1 },
  { id: "board-question", phase: "entities", title: "Find the owner of cell rules", eyebrow: "Test ownership", minutes: 1 },
  { id: "board-entity", phase: "entities", title: "Make Board a class", eyebrow: "State owner", minutes: 1 },
  { id: "game-entity", phase: "entities", title: "Make Game the coordinator", eyebrow: "Workflow owner", minutes: 1 },
  { id: "player-entity", phase: "entities", title: "Keep Player as identity", eyebrow: "Stable values", minutes: 1 },
  { id: "cell-question", phase: "entities", title: "Decide whether Cell is a class", eyebrow: "Model with restraint", minutes: 1 },
  { id: "cell-entity", phase: "entities", title: "Keep Cell as a field", eyebrow: "Reject needless objects", minutes: 1 },
  { id: "enums-entity", phase: "entities", title: "Model closed choices as enums", eyebrow: "Value types", minutes: 1 },
  { id: "winning-rule-entity", phase: "entities", title: "Leave out a premature interface", eyebrow: "Avoid abstraction", minutes: 1 },
  { id: "ownership-rule", phase: "entities", title: "Keep rules beside their data", eyebrow: "Ownership heuristic", minutes: 1 },
  { id: "winning-rule-check", phase: "entities", title: "Explain why WinningRule waits", eyebrow: "Test your reasoning", minutes: 1 },
  { id: "entity-flow", phase: "entities", title: "See one move cross the objects", eyebrow: "Entity flow", minutes: 1 },
  { id: "entity-flow-story", phase: "entities", title: "Read the arrows as a story", eyebrow: "Responsibility flow", minutes: 1 },
  { id: "game-design-intro", phase: "class-design", title: "Move from entities to APIs", eyebrow: "Design bridge", minutes: 1 },
  { id: "game-design", phase: "class-design", title: "Derive Game state and methods", eyebrow: "Requirement to API", minutes: 2 },
  { id: "game-design-two", phase: "class-design", title: "Derive Game actions and results", eyebrow: "Requirement to API", minutes: 1 },
  { id: "board-design", phase: "class-design", title: "Derive Board validation APIs", eyebrow: "Cell ownership", minutes: 1 },
  { id: "board-design-two", phase: "class-design", title: "Derive Board result APIs", eyebrow: "Cell ownership", minutes: 1 },
  { id: "pattern-decisions", phase: "class-design", title: "Reject patterns without variation", eyebrow: "Pattern discipline", minutes: 2 },
  { id: "pattern-future", phase: "class-design", title: "Add Strategy only when needed", eyebrow: "Future variation", minutes: 1 },
  { id: "pattern-check", phase: "class-design", title: "Recognize justified Strategy", eyebrow: "Test your reasoning", minutes: 1 },
  { id: "implementation-map", phase: "implementation", title: "Separate workflow from cell rules", eyebrow: "Code map", minutes: 1 },
  { id: "implementation-flow", phase: "implementation", title: "Trace one move through the code", eyebrow: "Execution order", minutes: 1 },
  { id: "validation-order", phase: "implementation", title: "Order one safe move", eyebrow: "Interactive workflow", minutes: 2 },
  { id: "validation-rule", phase: "implementation", title: "Validate before changing state", eyebrow: "Core invariant", minutes: 1 },
  { id: "ownership-concept", phase: "implementation", title: "Separate Board and Game rules", eyebrow: "Encapsulation", minutes: 1 },
  { id: "enum-concept", phase: "implementation", title: "Prefer precise states", eyebrow: "Enums", minutes: 1 },
  { id: "pattern-concept", phase: "implementation", title: "Keep the first implementation direct", eyebrow: "Pattern restraint", minutes: 1 },
  { id: "value-types", phase: "implementation", title: "Read the three value types", eyebrow: "Java code", minutes: 1 },
  { id: "move-result-check", phase: "implementation", title: "Choose results over exceptions", eyebrow: "API semantics", minutes: 1 },
  { id: "player-code", phase: "implementation", title: "Keep Player immutable", eyebrow: "Java code", minutes: 2 },
  { id: "board-placement-code", phase: "implementation", title: "Validate and place a mark", eyebrow: "Board.java", minutes: 2 },
  { id: "board-win-code", phase: "implementation", title: "Check every winning line", eyebrow: "Board.java", minutes: 2 },
  { id: "board-support-code", phase: "implementation", title: "Read, fill, and reset Board", eyebrow: "Board.java", minutes: 2 },
  { id: "game-overview", phase: "implementation", title: "Find the safe turn switch", eyebrow: "Game coordinator", minutes: 1 },
  { id: "game-setup-code", phase: "implementation", title: "Construct a valid Game", eyebrow: "Game.java", minutes: 2 },
  { id: "game-guards-code", phase: "implementation", title: "Reject before mutation", eyebrow: "Game.makeMove", minutes: 2 },
  { id: "game-result-code", phase: "implementation", title: "Resolve an accepted move", eyebrow: "Game.makeMove", minutes: 2 },
  { id: "game-support-code", phase: "implementation", title: "Reset and expose Game state", eyebrow: "Game.java", minutes: 1 },
  { id: "demo-code", phase: "implementation", title: "Use the public API", eyebrow: "TicTacToeDemo.java", minutes: 2 },
  { id: "scenario-happy", phase: "implementation", title: "Trace a complete win", eyebrow: "Scenario proof", minutes: 2 },
  { id: "scenario-rejection", phase: "implementation", title: "Prove rejected state is unchanged", eyebrow: "Invariant proof", minutes: 1 },
  { id: "scenario-check", phase: "implementation", title: "Identify the full invariant", eyebrow: "Test your reasoning", minutes: 1 },
  { id: "simulator-lab", phase: "implementation", title: "Challenge the model", eyebrow: "Interactive lab", minutes: 3 },
  { id: "extension-strategies", phase: "extensions", title: "Add computer move strategies", eyebrow: "Changed requirement", minutes: 2 },
  { id: "extension-board", phase: "extensions", title: "Generalize the board and win rule", eyebrow: "Changed requirement", minutes: 1 },
  { id: "extension-state", phase: "extensions", title: "Extend history and coordination", eyebrow: "Changed requirements", minutes: 2 },
  { id: "extension-answer", phase: "extensions", title: "Explain the design aloud", eyebrow: "Interview response", minutes: 1 },
  { id: "extensions-check", phase: "extensions", title: "Choose the smallest extension", eyebrow: "Final check", minutes: 1 },
];
